### ISSUE TITLE
Please make a "donate" button available somewhere on your site or your GitHub repo

### ISSUE THREAD

**Issue by webmat** [ridiculousfish/HexFiend#1]
Hex Fiend is really saving my day at the moment and I don't know how to thank you.

Oh wait: "thank you" :-)

Still, donate button plz!

Cheers

Mat

**Comment by KingSupernova31** [comment]
I'll add my thanks here as well; so many "modern" editors completely fall apart when handling large files, and HexFiend has been incredibly useful in my work. I would happily donate if a link were made available, but in the absence of that, please accept my gratitude. :)
