### ISSUE TITLE
Update improperly signed

### ISSUE THREAD

**Issue by alehed** [ridiculousfish/HexFiend#102]
When updating HexFiend through the sparkle dialog, I get a message that the update is not properly signed.

![update_error](https://user-images.githubusercontent.com/10847473/29430415-98c441ce-8394-11e7-8f8e-ff8908bf9294.jpeg)

Version: Version 2.3.0 (300)
Installed via Homebrew Cask.

Anybody else having this issue?

**Comment by kainjow** [comment]
The auto update version only works from version 2.7 and up.

Also, the Homebrew Cask version is unofficial and unsupported.

**Comment by alehed** [comment]
Ok. I'll get it from the website then.
