### ISSUE TITLE
Updated icon

### ISSUE THREAD

**Issue by daylightbrightledlight** [ridiculousfish/HexFiend#104]
I wanted to suggest updating the Hex Fiend icon so that it can look nice on higher-resolution displays. This is evident on macOS, where the Hex Fiend icon is low resolution.

**Comment by daylightbrightledlight** [comment]
See https://github.com/ridiculousfish/HexFiend/blob/master/app/resources/hex_icon.icns

The icon appears to be distorted on macOS as well.

**Comment by kainjow** [comment]
What do you mean "distorted"? It will look blurry on Retina displays simply because it is too low resolution.

If @ridiculousfish doesn't have a larger version then we'd need to generate a new icon. Any graphic designers out there? :)

**Comment by ridiculousfish** [comment]
We have the original PSDs in house. New updated version incoming…

**Comment by daylightbrightledlight** [comment]
> What do you mean "distorted"?

@kainjow The icon is wider and more stretched out than the actual logo. See http://ridiculousfish.com/hexfiend/images/hex_icon.png.

**Comment by gingerbeardman** [comment]
@daylightbrightledlight is correct @kainjow @ridiculousfish it seems the current icon has been stretched to fit

**Comment by kainjow** [comment]
@ridiculousfish any update on the high-res icon?

**Comment by gingerbeardman** [comment]
If it's lost, or for any other reason, I'd be happy to redraw it and submit a pull

**Comment by ridiculousfish** [comment]
Whew, what a week...

Here's what she came up with, a modern spin on a classic icon. She is eager to hear any feedback.

![hex icon new jpg](https://user-images.githubusercontent.com/920838/32695606-432b6fe8-c715-11e7-93b7-b8fe5ca632b9.jpeg)

![hex icon small jpg](https://user-images.githubusercontent.com/920838/32695608-4c929534-c715-11e7-9d49-278c753f2cdf.jpeg)

**Comment by nsknyc** [comment]
This looks great!! I love the idea. The curves on the crowbar and line on the blue button need to be smoother. Although, I highly doubt anyone will see it when reduced in size.

**Comment by ridiculousfish** [comment]
she's going to rework some of the lines

**Comment by gingerbeardman** [comment]
How does it look in the dock amongst other icons? And in finder in list view?

**Comment by ridiculousfish** [comment]
Mockup:

![unnamed](https://user-images.githubusercontent.com/920838/32763782-a5500e70-c8b6-11e7-8342-7df6aadbd5ed.png)

**Comment by kainjow** [comment]
I think it looks nice! 👍

**Comment by gingerbeardman** [comment]
I don't get why the blue thing is for?

**Comment by ridiculousfish** [comment]
![unnamed-1](https://user-images.githubusercontent.com/920838/34288309-50837248-e6a1-11e7-8b67-1d319a9059f5.png)

latest, no blue thing

**Comment by kainjow** [comment]
Looks good. Do you have a 1024x1024 version?

**Comment by gingerbeardman** [comment]
Crowbar shadow is cropped at the bottom of icon
