### ISSUE TITLE
Search control buttons truncated on High Sierra

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#108]
Replace All/Replace/Replace & Find/Previous/Next buttons are truncated when running on 10.13

Resizing the window does not correct the layout

<img width="778" alt="screen shot 2017-09-26 at 09 40 30" src="https://user-images.githubusercontent.com/49612/30851663-2e5fd57e-a2a1-11e7-8f03-66577f4c9168.png">

**Comment by kainjow** [comment]
If anyone wants to investigate this bug, feel free. It may be a while before I can look into it since I'm still on 10.12 and attempting to upgrade to 10.13 results in an error on my computer.

**Comment by kainjow** [comment]
Bought a new Mac with 10.13, can reproduce now. Will look into a fix soon.
