### ISSUE TITLE
Text search is case sensitive.

### ISSUE THREAD

**Issue by grylem** [ridiculousfish/HexFiend#109]
Now HexFiend search text string case sensitive. Its possible change search text case sensitive?
If text is 'TEST' now i cannot find it with search 'test'
Thanks.

**Comment by kainjow** [comment]
I added a very basic version of this but it's hidden behind a preference that doesn't have a UI. You can turn it on with:

    defaults write com.ridiculousfish.HexFiend CaseInsensitiveSearch -bool YES

This setting applies immediately for the next time you perform a search.

It's implemented using an existing slow algorithm so it'll be fine for tiny files but terrible for anything more. Can improve performance later if anyone finds this potentially useful.

**Comment by FreddieOliveira** [comment]
This doesn't work. If I run

`defaults read com.ridiculousfish.HexFiend CaseInsensitiveSearch` 

I can confirm the change was made, yet the search continues to be sensitive. Also, I think it's better to add it as on option along with the `Hex/Text` find options, instead of a hidden non-working feature.

**Comment by kainjow** [comment]
What version did you test with?

**Comment by FreddieOliveira** [comment]
macOS: Mojave 10.14.2
HexFiend: Version 2.9 (1528770943)

**Comment by kainjow** [comment]
It's in the 2.10 version. Please test the latest beta here: https://github.com/ridiculousfish/HexFiend/releases

**Comment by FreddieOliveira** [comment]
Hmm, thanks. Now it works. But still, why not to add a checkable option in the GUI instead of a hidden command

**Comment by kainjow** [comment]
As mentioned it's not a good implementation, just hacked onto of existing code. So don't want to make it very visible until it's improved.

Also UI might need some rearrangements to accommodate more options in the Find window.

**Comment by aleeraser** [comment]
Are there any updates on this?

**Comment by kainjow** [comment]
> Are there any updates on this?

Using https://github.com/HexFiend/HexFiend/issues/376 to track updates.
