### ISSUE TITLE
UTF-8 characters not shown even with correctly selected encoding

### ISSUE THREAD

**Issue by nobodo** [ridiculousfish/HexFiend#111]
It's showing just dots instead of the correct characters.

**Comment by kainjow** [comment]
Can you provide a sample file or a screenshot?

**Comment by RamiroOliva** [comment]
In fact it won't display any accent. Just create a new file and type some accented letters like á, é... they will be replaced by unaccented versions: a, e...

**Comment by kainjow** [comment]
@nobodo See #6.

@RamiroOliva please open a separate issue.

**Comment by kainjow** [comment]
Tracking this in #185
