### ISSUE TITLE
Search button group outside of container

### ISSUE THREAD

**Issue by krokofant** [ridiculousfish/HexFiend#112]
<img width="488" alt="skarmavbild 2017-11-17 kl 15 37 19" src="https://user-images.githubusercontent.com/5908498/32952391-70d5143e-cbad-11e7-8a20-26cde9ba30f4.png">

Version 2.5

**Comment by kainjow** [comment]
What OS?

**Comment by krokofant** [comment]
I thought this was only for macOS so I omitted that info. Using macOS 10.13

**Comment by kainjow** [comment]
Duplicate of #108
