### ISSUE TITLE
Website has version 2.4 for download

### ISSUE THREAD

**Issue by fingolfin** [ridiculousfish/HexFiend#114]
I just downloaded the "latest" version from http://ridiculousfish.com/hexfiend/ and after starting it, to my surprise learned from Sparkle that an update (to 2.8) was available. 

So the download link on the website is outdated.

**Comment by ridiculousfish** [comment]
Heh, yeah, the site is stale

**Comment by kainjow** [comment]
Could fix this by redirecting the site to the existing GitHub Pages one ;)

**Comment by ahyattdev** [comment]
Website download out of date again

**Comment by kainjow** [comment]
@ridiculousfish is the only one who can resolve this. Since he is aware of the issue, but not very active here, I'm closing this.

**Comment by ridiculousfish** [comment]
ridiculousfish.com/hexfiend/ now has latest 2.8

**Comment by panda-byte** [comment]
The link is outdated again (currently links to 2.14.0, while the latest is 2.14.1). This problem could be permanently solved by using `https://github.com/HexFiend/HexFiend/releases/latest/`, I think.

**Comment by ridiculousfish** [comment]
[Site has been updated](https://github.com/HexFiend/hexfiend-site/commit/2d8f5c1907f579191f45e5f992665f82570e9c8b). Unfortunately linking to latest doesn't work because the dmg file includes the version name.
