### ISSUE TITLE
Hex Fiend is for sale on mac app store

### ISSUE THREAD

**Issue by rogusdev** [ridiculousfish/HexFiend#115]
They changed the title but not the README summary that names Hex Fiend

![screen shot 2017-12-21 at 2 51 38 pm](https://user-images.githubusercontent.com/1178706/34272511-8b51abf8-e65e-11e7-858e-8cd676c4680c.png)

I imagine you can contact apple to have it taken down.

It looks like an ancient version as well.

**Comment by nsknyc** [comment]
I would not mind taking a look at the binary fingerprint, just to tear this guy a new one..

**Comment by ridiculousfish** [comment]
This again :|

**Comment by kainjow** [comment]
This issue keeps coming up, nothing we can do here except for @ridiculousfish as he's the copyright owner. Closing.
