### ISSUE TITLE
Problem opening drive on macos X 10.10.5

### ISSUE THREAD

**Issue by germainm** [ridiculousfish/HexFiend#117]
when opening drive i got this message:

The operation couldn’t be completed. (CFErrorDomainLaunchd error 2.)

somebody has an idea what the problem is ?

Thanks for your help

**Comment by kainjow** [comment]
What version of Hex Fiend?

**Comment by germainm** [comment]
version 2.8

**Comment by kainjow** [comment]
Are you using the version downloaded from this GitHub releases page?

**Comment by kainjow** [comment]
Closing due to no response.
