### ISSUE TITLE
Jump, move and selected byte in Hex

### ISSUE THREAD

**Issue by deladriere** [ridiculousfish/HexFiend#118]
Is there a way to jump to a location in hex instead of decimal?

**Comment by kainjow** [comment]
Yes, just use "0x" in the beginning, for example "0x42".

**Comment by kainjow** [comment]
In 282edb504d5bd2d2a79fc3cf42346c0131b0baf1 I set the text fields' placeholder text as examples, since octal is also supported:

<img width="519" alt="screen shot 2018-01-20 at 3 12 33 pm" src="https://user-images.githubusercontent.com/271035/35188911-879ddda8-fdf4-11e7-9a95-5e2e3cfe40cb.png">
