### ISSUE TITLE
toggling binary templates and size of window

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#121]
it would be great if toggling templates changed the size of the window to accommodate, rather than squishing everything in to fit.

i like to have my hex aligned to 0,10,20 etc and it all gets messed up when toggling and i lose my place 

also, toggling it on and off, the window is a different size to what it was originally

thanks

**Comment by kainjow** [comment]
yeah the current "layout manager" is funky with how this works, since it appears to try and keep the window size, which generally isn't what is wanted.

Eventually it'd be nice to replace all layout code with Auto Layout and NSStackView, but that's a big job.
