### ISSUE TITLE
Cannot type non-hex characters when using certain encodings (error "unknown encoding")

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#122]
A
1. Open Find/Replace
2. Set mode to TEXT
3. Try typing in the find field
4. nothing appears (though you can backspace over any previously entered text)

B
1. Open Find/Replace
2. Set mode to HEX
3. Try typing in the find field
4. hex can be typed

Affects
Version 2.8 (170719)
Version 2.9 (180121)

**Comment by kainjow** [comment]
I can't reproduce. I'm able to type just fine. What are you typing? Can you paste text? Does it work with a new empty document?

**Comment by gingerbeardman** [comment]
Hmm. I can't paste text either.
I'm just typing plain English using the keyboard.

Strangely it works if I log in to a new user (guest user account). Will investigate. I'll leave this open until I find the cause/solution.

**Comment by gingerbeardman** [comment]
OK, this was related to my Japanese encoding testing. I had left encoding set to one of the more obscure Japanese encodings.


![screen shot 2018-02-12 at 10 47 12](https://user-images.githubusercontent.com/49612/36093294-1d025b18-0fe2-11e8-9717-e040375b2d6d.png)

When typing with no text appearing Console reported a big clue:

```
default	10:44:21.503112 +0000	Hex Fiend	Unknown encoding 2147485731
```

Setting encoding to something more sane (even Japanese-JIS) means I can not type OK.

Leaving open because still seems like a bug.

**Comment by kainjow** [comment]
It's not really a bug, since that encoding (https://en.wikipedia.org/wiki/JIS_X_0213) doesn't handle ASCII characters it seems. I added an alert in this case showing that the text conversion failed.

**Comment by gingerbeardman** [comment]
Also, related and probably not worth a new bug...

I can Cmd+click the selected other encoding and then there are no encodings selected (but it's still using the one you last selected)

**Comment by kainjow** [comment]
Go ahead and make a separate issue.
