### ISSUE TITLE
Alignment of line numbers is too low/high

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#123]
Here it is using the different fonts it lists on my setup.

![screen shot 2018-02-12 at 10 27 37](https://user-images.githubusercontent.com/49612/36092582-c2d4bdea-0fdf-11e8-8a17-f1ab0c982f9f.png)

![screen shot 2018-02-12 at 10 27 54](https://user-images.githubusercontent.com/49612/36092583-c2efe1d8-0fdf-11e8-84c6-111daecc6d57.png)

![screen shot 2018-02-12 at 10 28 01](https://user-images.githubusercontent.com/49612/36092584-c309eeb6-0fdf-11e8-96ca-bf1c20dd32cf.png)

![screen shot 2018-02-12 at 10 28 38](https://user-images.githubusercontent.com/49612/36092585-c320189e-0fdf-11e8-9095-201628b26e2f.png)

![screen shot 2018-02-12 at 10 28 51](https://user-images.githubusercontent.com/49612/36092586-c33e9490-0fdf-11e8-8b23-6e143c73ac55.png)

![screen shot 2018-02-12 at 10 29 01](https://user-images.githubusercontent.com/49612/36092587-c3567fec-0fdf-11e8-80da-bc6d76292bcd.png)

![screen shot 2018-02-12 at 10 29 14](https://user-images.githubusercontent.com/49612/36092588-c36d0294-0fdf-11e8-9d66-02ef4e4a9b87.png)

**Comment by kainjow** [comment]
Unfortunately the line numbers are drawn entirely differently than the hex text, and so to properly fix this it would need to be refactored to use the same text renderer, but that text renderer is meant for fixed-width drawing, and the line numbers are drawn as normal text, so it's a tricky fix..

**Comment by kainjow** [comment]
Should be fixed with 65217975441048aeb6df84561cb37c108760e867 and 7f251f4c790fa2c309bdea1e3ff6c06631d8d113

The line numbers were being drawn centered, but were off by one point for some reason. However the hex/plain text were not centered, although sometimes it looks like it was. Resolving both of these fixes the issue.

Happy New Year! 🎉
