### ISSUE TITLE
It's possible to select zero encodings

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#125]
I can Cmd+click the selected other encoding and then there are no encodings selected (but it's still using the one you last selected)

**Comment by RobertoMachorro** [comment]
Are you talking about the *Choose Encoding* window below?

![image](https://user-images.githubusercontent.com/7190436/37040308-8578ca78-2127-11e8-808a-17aff3873e1d.png)

If so, to confirm, you are unselecting the currently selected option, leaving nothing selected? Is the expected outcome, to not allow such de-selection?

**Comment by gingerbeardman** [comment]
> If so, to confirm, you are unselecting the currently selected option, leaving nothing selected? 
Yes.

> Is the expected outcome, to not allow such de-selection?
Either that, or if none are selected default back to ASCII?

**Comment by RobertoMachorro** [comment]
OK, I'm going to get this done. @ridiculousfish any preference on the expected outcome on deselection? or should I just not allow it to happen?

**Comment by RobertoMachorro** [comment]
OK, there's a fix at Pull Request #126 

Defaults to MacRoman encoding, just like HexFiend does on startup.

**Comment by kainjow** [comment]
Since the search can change the listing, there needs to be support for no selection. However I don't know if deselecting should really change anything in this situation. I feel like only a new selection should make a change.

Another idea is the window could have a field that shows the current encoding, and a button to Apply, but that's Windows behavior :)

**Comment by gingerbeardman** [comment]
My main issue was that it wasted my time trying to figure out the state of the app. So anything that plugs holes in the UI gets my vote.

**Comment by kainjow** [comment]
Maybe we just copy what TextEdit does where the encodings window is essentially a "favorites" window:

<img width="505" alt="screen shot 2018-03-11 at 6 01 24 pm" src="https://user-images.githubusercontent.com/271035/37261055-7cc4bb16-2556-11e8-8062-1806a088b4e1.png">

<img width="387" alt="screen shot 2018-03-11 at 6 01 35 pm" src="https://user-images.githubusercontent.com/271035/37261046-63497f96-2556-11e8-9254-60b81228d500.png">

**Comment by kainjow** [comment]
I'm going to close this. I don't think it's a significant issue. If it becomes an issue for others in the future we can revisit, or if someone wants to implement the suggested change above feel free.

**Comment by gingerbeardman** [comment]
I respectfully disagree it's not an issue, given that I wasted a good amount of time figuring out the current hidden behaviour. IMHO
