### ISSUE TITLE
Changelog from autoupdate shows beta info

### ISSUE THREAD

**Issue by aonez** [ridiculousfish/HexFiend#127]
I had 2.7 version and autoupdate told me 2.8 was released, but the changelog inside the notification shows 2.9 info. The update process worked and 2.8 is installed now, just felt strange to me to see the 2.9 info while it's in beta and it's not gonna be installed.

![screen shot 2018-03-14 at 11 51 22](https://user-images.githubusercontent.com/480163/37398378-9cd80f28-277e-11e8-9052-b08092dc431e.png)

Thanks for the amazing soft!

**Comment by kainjow** [comment]
Ah yes this is because the feed is pulling from the master branch, which should probably be changed to something less. However I'll try to release the 2.9 version soon.
