### ISSUE TITLE
Command line tool doesn't open the file

### ISSUE THREAD

**Issue by fact0real** [ridiculousfish/HexFiend#128]
Hey
In the more recent version of HexFiend, the command line tool, `hexf` doesn't open the given file as an argument.  Please verify this, I think there is a tiny bug, as you know the `hexf` file in recent version of HexFiend is not shell script and it's a macos binary file.
Thanks

**Comment by kainjow** [comment]
Looks like it doesn't work for relative paths, which is now fixed. As a workaround you can use something like `hexf $(pwd)/myfile.txt` for now.
