### ISSUE TITLE
Inspect Symbolic Links / Aliases files

### ISSUE THREAD

**Issue by mixage** [ridiculousfish/HexFiend#129]
Great software! :-)

Is there a way to inspect an alias / symlink file (without resolving) ?

**Comment by kainjow** [comment]
Currently no, but I added a preference to allow disabling alias resolving when opening file. This will let you access the "bookmark" data now.

For symbolic links I don't think there's a way to read the symbolic link as a file, but you can use `readlink` on the command line to view their contents.

**Comment by mixage** [comment]
Thanks :-)
