### ISSUE TITLE
Full Path in Title Bar

### ISSUE THREAD

**Issue by FrederickGeek8** [ridiculousfish/HexFiend#132]
This is a **feature request**. 

I think that it would be useful, if not necessary to have the full path displayed in the title bar of the application in the situation where two or more files of the same basename are open. Comparing two files, it is very confusing as to which file I am looking at any given time. I attached a file of the behavior in question.

I could probably submit a PR at some point, but right now I have my hands full with other things so it would take a while. I would welcome others submitting a PR if this is deemed important.

<img width="1133" alt="screen shot 2018-05-27 at 6 05 28 pm" src="https://user-images.githubusercontent.com/774597/40591084-990f6d52-61d8-11e8-8ebc-9774370911b7.png">

**Comment by kainjow** [comment]
I tested with TextEdit and it works the same. Since this appears to be default Cocoa NSDocument behavior, I'd prefer to keep it as it is.
