### ISSUE TITLE
Why HexFiend add user execution right to my resaved file automatically?

### ISSUE THREAD

**Issue by xiongmao86** [ridiculousfish/HexFiend#133]
I am using it today, version 2.8.0 from homepage. When I use it I notice some of my file rights are changed without notify me when I change a file and save it with 'save as' option. The 'save' option is fine though. This could be a issue.

**Comment by kainjow** [comment]
This is already fixed with version 2.9 (see #100). Can you try the latest version and confirm? https://github.com/ridiculousfish/HexFiend/releases/tag/v2.9.0-beta-4

**Comment by xiongmao86** [comment]
Sorry, I can't download version 2.9 now,  aws is block by fire wall. I'll try it when I can download the 2.9 version.

**Comment by xiongmao86** [comment]
I have try out 2.9, the issue is gone.
