### ISSUE TITLE
Binary template not remembered across launches

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#136]
- select a binary template
- quit app
- launch app

Expected
- binary template selected should be the same as before quit
- ideally it would also remember the structure of the tree that I had expanded in the template

Actual
- binary template selected is "None"

**Comment by wader** [comment]
For me it remembers the template but i have to reselect it to get the tree

**Comment by gingerbeardman** [comment]
Just to confirm what @wader said is still true with v2.13.0b2

**Comment by wader** [comment]
If your developing template scripts I use this [modd](https://github.com/cortesi/modd) configuration to automatically reload on changes:
```
WAV.tcl {
    prep: osascript \
        -e 'tell application "System Events"' \
	-e '    tell process "Hex Fiend"' \
	-e '        click pop up button 1 of window 1' \
	-e '        click menu item "WAV" of menu 1 of pop up button 1 of window 1' \
	-e '    end tell' \
        -e 'end tell'
}
```

**Comment by gingerbeardman** [comment]
@wader COOL, will look into modd

**Comment by wader** [comment]
Do it! best tool ever, saved me lots of hand movements 😄

**Comment by kainjow** [comment]
I'm unable to repro. Can you provide repro steps?

**Comment by gingerbeardman** [comment]
Best I can do right now is a short video:

https://imgur.com/xc1R4vt

**Comment by kainjow** [comment]
Hm still can't repro. How are you "restarting" the app and reopening the file?

**Comment by gingerbeardman** [comment]
- Cmd+Q to quit
- Then launch via Dock, or Alfred launcher

Here are my files: 
[Archive.zip](https://github.com/ridiculousfish/HexFiend/files/4402210/Archive.zip)
