### ISSUE TITLE
Binary templates: read data without labeling it

### ISSUE THREAD

**Issue by bvandergiessen** [ridiculousfish/HexFiend#137]
Great to see the new Binary templates in version 2.9! I have a few feature requests - most of them you have probably thought of yourself.

1. _Read data without labeling it_
Expanding on your PNG template, I tried to label sections based on their type (see below). But when the type is read into a variable in the Tcl script, it is also immediately labeled and put on screen, so an unwanted additional label comes into view above the section.
To allow for more sophisticated binary templates, it would be very useful if data could be read from the open file without being labeled.

2. _Scroll the hex view along with the template_
This one I'm sure you have already thought about: when clicking on something from the Binary template view, you'd want the hex bytes to be visible as well.

3. _Select bytes using the Binary template view_
It would be useful if you could change the (hex-view) selection to select the bytes that a certain label refers to, for instance by double-clicking the label in the Binary template view.

4. _Highlight entire section when section label selected_
A minor UI thing: when a label is selected in Binary template view, the corresponding bytes are highlighted in the hex view. This doesn't happen yet when a section header is selected.

5. _Interpretation column in Binary template view_
Another column in the Binary template view would be very useful, where the Tcl script can interpret the bytes to draw conclusions about what is going on. For example in the PNG template: when it gets "Color Type" = 3, the script could add a text in the third column that explains what color type 3 means. I'm not talking about a general "help" text, but a text based on the value. Scripts could show whether a CRC checksum is correct, etc.

The PNG template:
```tcl
big_endian
requires 0 "89 50 4E 47 0D 0A 1A 0A"
ascii 6 "Signature"
move 2
while {![end]} {
	move 4
	set type [ascii 4 ""]
	move -8
	switch $type {
		IHDR {set secname {Image header}}
		PLTE {set secname {Palette}}
		IDAT {set secname {Image data}}
		IEND {set secname {Image trailer}}
		tRNS {set secname {Transparency infomation}}
		gAMA {set secname {Image gamma}}
		cHRM {set secname {Primary chromaticities}}
		sRGB {set secname {Standard RGB color space}}
		iCCP {set secname {Embedded ICC profile}}
		tEXt {set secname {Textual data}}
		zTXt {set secname {Compressed textual data}}
		iTXt {set secname {International textual data}}
		bKGD {set secname {Background color}}
		pHYs {set secname {Physical pixel dimensions}}
		sBIT {set secname {Significant bits}}
		sPLT {set secname {Suggested palette}}
		hIST {set secname {Palette histogram}}
		tIME {set secname {Image last-modification time}}
		default {set secname {(Type unknown)}}
	}
	section "$secname" {
		set chunk_len [uint32 "Chunk Length"]
		set chunk_type [ascii 4 "Chunk Type"]
		if {$chunk_type == "IHDR"} {	;# Image Header
			set img_width [uint32 "Width"]
			set img_height [uint32 "Height"]
			set bitdepth [uint8 "Bit Depth"]
			uint8 "Color Type"
			uint8 "Compression Method"
			uint8 "Filter Method"
			uint8 "Interlace Method"
		} else {
			if {$chunk_len > 0} {hex $chunk_len "Chunk Body"}
		}
		hex 4 "CRC"
	}
}
```

**Comment by kainjow** [comment]
1. I think simplest way to implement this is to make the label argument optional, so if it's not present then it doesn't get added and just returns the value.

2. If you right-click an item you can select "Jump to Field" which I think does what you want. Problem is making this default might be annoying if you're scrolled somewhere but wanting to look at data elsewhere.

3. I think double-click would work here, and/or add a new context menu option.

4. I had this implemented, but since the template has the ability to move position within a section, not all items within a section necessarily fall within the same range. For most of the time though it'd probably make sense. I can look at bringing that back.

5. Sounds like a good idea. Maybe a "Notes" column?

**Comment by bvandergiessen** [comment]
> 1. I think simplest way to implement this is to make the label argument optional, so if it's not present then it doesn't get added and just returns the value.

Perfect!

> 2. If you right-click an item you can select "Jump to Field" which I think does what you want. Problem is making this default might be annoying if you're scrolled somewhere but wanting to look at data elsewhere.

I hadn't seen that yet. I guess it is a matter of taste - my thinking would be: if you want to look at hex from one part of the file and labels from elsewhere, you could scroll the label view without selecting something; when you actually _click_ on a label in the template view (or select it with an arrow key), you probably intend to look at the corresponding hex bytes. But it's up to your judgment.

> 3. I think double-click would work here, and/or add a new context menu option.

Great.

> 4. I had this implemented, but since the template has the ability to move position within a section, not all items within a section necessarily fall within the same range. For most of the time though it'd probably make sense. I can look at bringing that back.

That does complicate it. Perhaps selecting a section could highlight the parts that would be highlighted if every sub-item in the section were selected?

> 5. Sounds like a good idea. Maybe a "Notes" column?

"Notes" is neutral but sounds user-editable, "Meaning" is perhaps too specific... Hard to think of the perfect label.

Thinking through all this, I came up with number 6. _Raw bytes command_
Once you have implemented 1. and 5., the Binary templates become much more powerful. That would probably make it useful for the Tcl scripts to load any number of raw bytes from the file.

At the moment only the `ascii`, `utf16` and `hex` commands retrieve an arbitrary number of bytes. The ascii command can't be used for raw bytes: it returns incomplete data when a 0-byte is involved (it is implemented with an `NSString`, and a C string gets terminated by a 0-byte). Utf16 is really only valid for data in that encoding. Only the hex command can deliver the full data to Tcl, but a command like
```
set bts [binary decode hex [hex $len]]
```
looks and feels like a workaround. If a `bytes` command could be added, such that
```
set bts [bytes $len]
```
would work, it's more natural. (That would be the only such command that wouldn't accept an optional label, as 'raw bytes' is not a display format.)

**Comment by Wevah** [comment]
> If you right-click an item you can select "Jump to Field" which I think does what you want. Problem is making this default might be annoying if you're scrolled somewhere but wanting to look at data elsewhere.

Why not make it a preference? Even if there's no UI for it (requiring `defaults write`).

**Comment by kainjow** [comment]
In 07bea4c99dd45c8ab5b25b0905a50d4050ccf81f I made the label argument optional, so it can be used without adding it to the UI.

Here's a example that reads the first byte `n` then reads `n`-many bytes or until the end of the file:

```tcl
set n [uint8]
goto 0
for {set i 0} {![end] && $i < $n} {incr i} {
	uint8 "Byte $i"
}
```

**Comment by kainjow** [comment]
In 54c29c8cc14ed5239972bdf3bfba176b56aa3f38 I added the two selection features hidden under prefs which you can set via the command line:

    defaults write com.ridiculousfish.HexFiend BinaryTemplatesOnSelectionJump -bool YES

Equivalent to "Jump to Field" menu but on selection.

    defaults write com.ridiculousfish.HexFiend BinaryTemplatesOnSelectionSelect -bool YES

Equivalent to "Select Bytes" menu (new) but on selection.

If people find these useful I can add UI for them in the Preferences window.

**Comment by bvandergiessen** [comment]
Reading data without putting a label on it seems to work well!

I have a few miscellaneous remarks and questions:

- An apparent bug: I tried release 2.10b3, and the status bar seems greyed out.

- When Hex Fiend restarts, it now has the same binary template activated that was there before, but the template isn't actually run (it's just the active choice in the dropdown). Is that intentional?

- The message when a `require` statement fails looks just like a script crash - are you planning to change that into something like "Template not applicable"?

- Another thing I'm trying to understand: when you select a template from the dropdown and then select another one, running it on the same file, does the template script run in the same Tcl session, or does it spawn a fresh one? In other words, could variables that have been set by a template script, or modules imported by it, affect the running of other template scripts on the same file?
I have this question because (as a workaround for some other problem) I had to rename the `hex` command temporarily, and then rename it back, in the PNG script, and some errors arose when I ran the template again (changing to another one and then changing back).

**Comment by kainjow** [comment]
> An apparent bug: I tried release 2.10b3, and the status bar seems greyed out.

What macOS version? Would you be able to post a screenshot?

**Comment by kainjow** [comment]
> When Hex Fiend restarts, it now has the same binary template activated that was there before, but the template isn't actually run (it's just the active choice in the dropdown). Is that intentional?

It doesn't run if there is no content, which is what happens at startup when the untitled document is shown.

> The message when a require statement fails looks just like a script crash - are you planning to change that into something like "Template not applicable"?

yes, I can do that.

Regarding your last question, yeah, we should probably create a new interpreter for each run. Currently it's created once when the program launches. I'll fix that.

**Comment by kainjow** [comment]
A little test script to see if a new interpreter is created each time:

```tcl
if {[info exists n]} {
	set n [expr $n + 1]
	puts "Exists: $n"
} else {
	set n 0
	puts "Doesn't exist: $n"
}
```

For the first 3 runs it currently outputs:

> Doesn't exist: 0
> Exists: 1
> Exists: 2

Good find!

**Comment by bvandergiessen** [comment]
Here's a screenshot of v2.9 and v2.10b3. I'm on macOS 10.13.4.
<img width="322" alt="status bar" src="https://user-images.githubusercontent.com/11797190/42157245-7eab5350-7ded-11e8-8973-e3eba01d6ef5.png">

**Comment by bvandergiessen** [comment]
Just tested with the latest commit. The binary templates have come a long way in a short time!

A few things that struck me:

- Features 1, 2 and 6 from my request are completely functional. So is the "Template not applicable" message and the new Tcl shell every time a template is run.

- For 3, the context menu now has "Select Bytes". I think selecting the bytes by double-clicking the label would still be a good addition, because it is very logical/intuitive (double-click a word on a web page and it gets selected).

- 4 (highlighting an entire section): At the moment, all section labels are anchored to the start of the document. That creates a strange experience: when going through the labels with the arrow keys, the document jumps up and down as you pass a section label. I still think something like "highlighting all items in the section" or "highlighting all items in the section and all bytes in-between them (meaning: a contiguous block of bytes)" would make it more pleasant to use. If those are not desirable, perhaps the document position can simply be unchanged when a section label is selected.

Maybe I may add another one (this should be the final request): _7. Resizable template pane_: when resizing the window, it only affects the bytes and text view, but it would be useful to be able to change the width of the template results as well.

**Comment by bvandergiessen** [comment]
As the focus of development has understandably shifted to other important things (Dark mode, iOS compatibility), I would like to understand the next steps for the binary templates. In my opinion, the main improvement to be made is highlighting the _sections_ in a logical way - as noted above, I think the most logical and intuitive way is to set the section borders at the file offset when the `section` and `endsection` commands were given. It would amount to this patch:
```patch
diff --git a/app/sources/HFTemplateController.m b/app/sources/HFTemplateController.m
index 767de0f..2693cb7 100644
--- a/app/sources/HFTemplateController.m
+++ b/app/sources/HFTemplateController.m
@@ -359,10 +359,16 @@ - (unsigned long long)length {
 - (void)beginSectionWithLabel:(NSString *)label {
     HFTemplateNode *node = [[HFTemplateNode alloc] initGroupWithLabel:label parent:self.currentNode];
     [self.currentNode.children addObject:node];
+    node.range = HFRangeMake((self.anchor + self.position), 0);
     self.currentNode = node;
 }
 
 - (void)endSection {
+    if((self.anchor + self.position) > self.currentNode.range.location) {
+        HFRange range = self.currentNode.range;
+        range.length = (self.anchor + self.position - range.location);
+        self.currentNode.range = range;
+    }
     self.currentNode = self.currentNode.parent;
 }
```
which I will gladly submit as a pull request if that is more convenient. The section highlighting makes it clearer to the user what is going on and makes it easier to navigate a binary file in larger steps.

There are other possible improvements that would enhance the usefulness of the binary templates (some are above, some in #146), but I think the current version is already good enough for deployment.

Another matter is the distribution of templates (written by HexFiend authors as well as others). I imagine bundling them with the installer is one option, but the user has more freedom if they can be downloaded at will. Similar modules for the BBEdit programmers' editor are listed [on a webpage](https://www.barebones.com/support/bbedit/plugin_library.html) but hosted by their individual authors. In contrast, the makers of the 010 hex editor host all templates [on their site](https://www.sweetscape.com/010editor/repository/templates/) and ask for new templates to [be mailed in](https://www.sweetscape.com/010editor/repository/templates/submit.html). What are your thoughts on this?

**Comment by kainjow** [comment]
The iOS changes are/were an experiment. Maybe that'll continue, not sure. My main thoughts were it'd be cool to have Hex Fiend for iPad since it's clear iOS is becoming a more Pro-focused platform for Apple. Not sure if it'll go anywhere (some major drawing issues still exist). Dark mode support is done, minus any bugs that may come in. Lastly, my personal life has had some major changes recently so my free time has diminished and starting January may become almost nil. However, I want to get the 2.9 bugs fixed and released so hopefully can get that done soon.

I think selection enhancements for 2.9 can wait as it's not directly a bug. I had this implemented before but reverted it, so I can look at re-reverting it. You may want to consider starting a new thread for just that since this thread has become quite large and covering multiple issues.

Thanks for the feedback!

**Comment by kainjow** [comment]
Regarding distribution of templates, I think we should wait until the feature is more mature and some of the templates are more fleshed out.

I think the other issues in this thread have been resolved, therefore closing this. Let me know if there's anything missing (I'd prefer opening new threads per subject if possible, it's easier to track).
