### ISSUE TITLE
Compare window alignment problem

### ISSUE THREAD

**Issue by mskressin** [ridiculousfish/HexFiend#141]
If you use the compare feature to compare two files, the resulting dialog does not properly display one of the files. The file on the right  does not have any way to see the top  of the file. The display is truncated. 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/18367653/43142782-6cfa0d56-8f16-11e8-9c77-cd7849867916.png">

**Comment by nneonneo** [comment]
Yeah something's definitely up with it. Running 2.10b5:

<img width="637" alt="screen shot 2018-07-27 at 10 48 28 am" src="https://user-images.githubusercontent.com/75449/43327919-bb0c9d76-918a-11e8-9d4d-74a7a33151da.png">
<img width="637" alt="screen shot 2018-07-27 at 10 48 35 am" src="https://user-images.githubusercontent.com/75449/43327923-be6c7a5e-918a-11e8-912b-240854c52287.png">

The alignment is wrong, and for me the left file has an entire column cut off.

**Comment by kainjow** [comment]
yeah something funky is going on here. I'll look into it.

**Comment by nneonneo** [comment]
Any update on this? I'm getting bitten by this pretty hard right now.

**Comment by nneonneo** [comment]
Ah, yes, 2.9 works fine. Thanks - I'll keep that version installed from now on.

**Comment by kainjow** [comment]
8c58dbde9ad56ee4770615ad41e2b40cf112de53 introduces this bug.

**Comment by kainjow** [comment]
Found the culprit: https://github.com/ridiculousfish/HexFiend/blob/ae11e0cb2218643de45c0abb8e7e7a2dad219b99/app/sources/BaseDataDocument.m#L999

**Comment by kainjow** [comment]
I've posted a new beta which should fix this. Please verify: https://github.com/ridiculousfish/HexFiend/releases

**Comment by mskressin** [comment]
Looks fixed to me. Thank you!
