### ISSUE TITLE
hexf feature suggestions

### ISSUE THREAD

**Issue by nneonneo** [ridiculousfish/HexFiend#143]
1. `hexf` should foreground the Hex Fiend app and window. This is what `open -a` does, for example. If I enter hexf on a Terminal the default expectation is that I will want to edit the file immediately. (You could add a `-b/--background` flag to leave Hex Fiend in the background, or reverse it and have a foreground flag for new behaviour)
2. `hexf` should have a help page (`hexf -h/--help`) to list the options, including the new `-d` option. This would help discoverability.
3. It would be nice to be able to specify the insertion/overwrite mode of the opened file.
4. It would be nice to be able to pipe data to `hexf` and have it open the data in a new untitled document. This would make it possible to use `hexf` as a nice graphical `xxd`/`hexdump` replacement.

I'd be happy to contribute some of these if there's a desire for them.

**Comment by kainjow** [comment]
Just fixed 1 in 4f3f8d79366433f10f57304ffff0719eb7fec0a5

I'll take a look at 2 and 3.

I'll track 4 in #144

**Comment by kainjow** [comment]
Usage was added a while back to hexf.

Closing for now.
