### ISSUE TITLE
Console support

### ISSUE THREAD

**Issue by BSVogler** [ridiculousfish/HexFiend#144]
It would be really cool, if I could pipe some strings into Hex Fiend via the console. You know for some GUI tools e.g. with TextMate you can e.g. `nvram -p | mate` to load the nvram to your editor or any other text. I have only experience in augmented reality and games development and not so much system applications development. I could do this by myself If I would know how this interface’s name is. Is the pipe used automatically like a launch parameter?

I think an install button in the settings would work well
![bildschirmfoto 2018-07-26 um 11 06 00](https://user-images.githubusercontent.com/801818/43252905-ea62d850-90c3-11e8-8b6b-e74d80a4234e.png)
. This is also how Github and TextMate do this. :)

**Comment by kainjow** [comment]
Just posted a new beta with this functionality: 
https://github.com/ridiculousfish/HexFiend/releases/tag/v2.10b5

(@nneonneo)

**Comment by nneonneo** [comment]
`cmd | hexf` works great - thanks for the quick feature implementation!
