### ISSUE TITLE
hexf -d doesn't work anymore

### ISSUE THREAD

**Issue by nneonneo** [ridiculousfish/HexFiend#145]
In 2.10b5, `hexf -d` appears broken. It accepts the inputs and launches Hex Fiend, but no diff window is shown.

Also, there's bugs when passing the wrong number of arguments:

- If you pass zero arguments, it says `Missing argument for "-d"`. This should probably say `Not enough arguments: diff mode "-d" requires exactly two arguments`.
- If you pass one argument, it crashes:
```
2018-07-27 10:51:41.836 hexf[62789:2229923] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa34d52cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb82f048d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffa33cb104 -[__NSPlaceholderArray initWithObjects:count:] + 276
	3   CoreFoundation                      0x00007fffa33d2c74 +[NSArray arrayWithObjects:count:] + 52
	4   hexf                                0x000000010d26697c -[Controller processArguments:] + 777
	5   hexf                                0x000000010d266e63 main + 202
	6   libdyld.dylib                       0x00007fffb8bd6235 start + 1
	7   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```
- If you pass three or more arguments, it says `Only one file can be specified when diff argument is used.` This should probably say something like `Too many arguments: diff mode "-d" requires exactly two arguments`.

**Comment by kainjow** [comment]
Looks like `-d` worked for absolute paths, just not relative. Same issue as #128. All these issues have been fixed as of 37345a57ac4bc486210d930e0951f6bf945d81cc. Thanks!
