### ISSUE TITLE
Compile error on Xcode 9.4.1

### ISSUE THREAD

**Issue by dplr** [ridiculousfish/HexFiend#150]
Hello,
From a fresh git checkout, using Xcode 9.4.1 Build version 9F2000, MacOS 10.13.6, I get the following compilation error:

```
HexFiend/framework/sources/HFTextRepresenter.m:34:29: error: no
      known class method for selector 'alternatingContentBackgroundColors'
            return [NSColor alternatingContentBackgroundColors];
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

```

Is there a known workaround ?

**Comment by kainjow** [comment]
You can comment out that line of code for now. Currently the project requires Xcode 10 to build.

**Comment by dplr** [comment]
OK thanks!
