### ISSUE TITLE
New windows get gradually narrower

### ISSUE THREAD

**Issue by erikbs** [ridiculousfish/HexFiend#155]
When I open new HexFiend windows, each new window is about one byte group narrower than the one that was active before the new window was opened. If no other windows are open, the new window will be just as wide as the last one that was open (expected behaviour). Likewise, file windows that are opened simultaneously will all have the same width (although narrower than the existing windows, if any). This is not a serious bug, but it is annoying enough.

In this case I opened the two text files included in the DMG and compared them:

![image](https://user-images.githubusercontent.com/5731506/47114100-2df9c280-d25b-11e8-9fab-546c6728287d.png)

The problem affects at the latest release and has been there at least since version 2.9. I am running OS X 10.9.5 and have been doing that since it first appeared (I know that it does not exist in version 2.1.2). The screenshot is from the latest beta (5) of version 2.10, which also has a visual bug that I do not see in version 2.9, i.e. extra, unused space on the right (new windows shrink by approximately that much):

![image](https://user-images.githubusercontent.com/5731506/47115098-d7da4e80-d25d-11e8-856a-73e5e8bf5b01.png)

**Comment by kainjow** [comment]
Thanks for reporting. There's an existing thread #141 so I'll close this as a dupe.
