### ISSUE TITLE
feature request: custom length byte grouping

### ISSUE THREAD

**Issue by yetzt** [ridiculousfish/HexFiend#159]
can you please allow custom byte groupings? not everything is three or a power of two.

**Comment by kainjow** [comment]
What number are you wanting to use? Just thinking it might be easier to add more manual entries to that menu than to support any number (also not sure if the code would behave oddly with a non power of two).

**Comment by kainjow** [comment]
Did some testing and it seems to work fine with arbitrary numbers, so I added this in.

**Comment by yetzt** [comment]
thanks! (my particular usecase was 6 bytes)
