### ISSUE TITLE
Is HexFiend by Peter Ammon on the Mac App Store the official version?

### ISSUE THREAD

**Issue by jakob** [ridiculousfish/HexFiend#161]
I just searched for Hex Fiend on the Mac App Store, and found this version from Peter Ammon:

https://itunes.apple.com/at/app/hex-fiend/id1342896380?mt=12

There is no mention on the Hex Fiend website of Peter Ammon, or of a Mac App Store distribution.

So I wonder if this is legit? Looking through the issues, there have been a bunch of forks of Hex Fiend on the Mac App Store that violated the BSD license. Is this version from Peter Ammon official? The "support" link on the Mac App Store goes to http://ridiculousfish.com/hexfiend/

If this version is from someone affiliated to the project, would it be possible to update the Hex Fiend website and provide a link to the Mac App Store download?

If this is unaffiliated, could you put a small note on the website that Hex Fiend is not available on the Mac App Store and any version distributed there are from unrelated 3rd parties that may or may not be trusted?

**Comment by ridiculousfish** [comment]
Yes that one is actually real and published by me.

I’ll update the website when I get a chance.

Thanks!

**Comment by FrankKooij** [comment]
The Mac App Store version was released almost a year ago. Since then the Hex Fiend releases in this GitHub repository have progressed from v2.8.0 to 2.11.0. Would you consider updating the Mac App Store version also? Thanks in advance.
