### ISSUE TITLE
Z_MEM_ERROR should probably be Z_BUF_ERROR

### ISSUE THREAD

**Issue by Wevah** [ridiculousfish/HexFiend#163]
If I'm reading the code for the `command_zlib_uncompress` case right, and the intent is to check for `data` not being large enough, the comparison to `Z_MEM_ERROR` on line 372 of HFTclTemplateController.m should actually be comparing to `Z_BUF_ERROR`.

**Comment by kainjow** [comment]
I think you're right. Good catch. I'll test and fix.
