### ISSUE TITLE
Feature Request: Specify Endianness of Raw Bytes in Template.

### ISSUE THREAD

**Issue by Wikiemol** [ridiculousfish/HexFiend#174]
Currently, it seems there is no way to specify endianness for raw bytes in tcl templates. The `big_endian` and `little_endian` commands don't affect them. 

I imagine this is the correct behavior and not a bug, as you wouldn't want this command to affect raw strings of ascii for example. However, this means that there is no way to specify both the number base and the endianness of the data at the same time in the template, E.g. a uint32 as both hex and little endian. This is counter intuitive since this can be done in the data inspector.

**Comment by kainjow** [comment]
Can you give an example of what you’re trying to do?

**Comment by Wikiemol** [comment]
Upon looking at the source here: https://github.com/ridiculousfish/HexFiend/blob/master/app/sources/HFTclTemplateController.m

It appears that the big_endian and little_endian commands just set a flag, and that endianness can be switched throughout the template. 

This means that the simplest way to add this feature would probably be to somehow apply the endianness to raw bytes as well, (not familiar enough with objective-c to know the best way how off the top of my head, but perhaps as it is done [here])(https://github.com/ridiculousfish/HexFiend/blob/14a4821f60a92d5ab61990125b34cabc3659f3dd/app/sources/HFTclTemplateController.m#L276). 

The documentation in the reference is a bit unclear, so perhaps an example could be provided there as well, as I didn't realize originally that this is how the command worked.

@kainjow Saw your comment as I was typing this. My machine is little_endian, I am trying to write a Mach-O template and the "magic" number for Mach-O is 0xFEEDFACF. Clearly, the best way to show this is in the correct byte order and also in Hex (since this spells out Feed Face), but since my machine is little endian, it appears as 0xCFFAEDFE. Another example is when dealing with little endian bit masks, which are also useful in the Mach-O specification.

**Comment by Wikiemol** [comment]
Also, I'd be happy to work this feature if you'd like. I really enjoy this project and would like to contribute!

**Comment by kainjow** [comment]
I got a basic implementation done in 978c7f678cec4ff8e9260f9383ba483a1839292e - working on improving it.

**Comment by kainjow** [comment]
Finished this in 892c5d7361418743c036fd280f68884505d98ad3 and 9385b6449eea3408067fed42df86546fa4476b04.

**Comment by Wikiemol** [comment]
Tried it out! Works great!
