### ISSUE TITLE
Feature Request: Set default tcl working directory to the template directory for tcl templates

### ISSUE THREAD

**Issue by Wikiemol** [ridiculousfish/HexFiend#176]
I am currently writing a Mach-O template for hex fiend, and it is getting a bit complex. To manage complexity, I would like to start putting some of the logic in a separate file. It makes sense to keep these files in my template directory, but in order to do that I have to add a 'cd' command in TCL to the absolute path of my template directory, and then use the "source" command. This limits reusability, as anyone who wanted to use my template would have to change that "cd" command themselves. 

It would make more sense to either make the template directory the default working directory, or at least make the absolute path to the template directory a globally defined variable (perhaps in an HF namespace or something like that).

I don't know this code base very well, but I did a test of this feature by taking the "templatesFolder" method from HFBinaryTemplateController and moving it to a shell class in AppUtilities and making it static. Then, used Tcl_Eval to call the cd command on the path that it returns in the evaluateScript method in HFTclTemplateController. This could be a possible implementation.

**Comment by kainjow** [comment]
I changed it to it sets the templates folder as the working directory during script evaluation.
