### ISSUE TITLE
Feature Suggestion: `sectionvalue` command

### ISSUE THREAD

**Issue by Wevah** [ridiculousfish/HexFiend#177]
I'd find the ability to set a computed display value for a section useful (it could also reduce initial clutter). For example, in the TGA extension area:

```tcl
section "Software" {
    set softwareID [ascii 41 "Software ID"]

    section "Software Version" {
        set versionNumber [uint16 "Version * 100"]
        set versionLetter [ascii 1 "Version Letter"]
        set versionString "[expr {$versionNumber / 100}].[expr {$versionNumber % 100}]$versionLetter"
        sectionvalue $versionString
    }
    
    sectionvalue "$softwareID $versionString"
}
```

I have working code for this if this is something worth adding. My current implementation also won't auto-expand sections with values set. It displays (when expanded) as:

![screen shot 2019-01-04 at 8 25 11 pm](https://user-images.githubusercontent.com/130825/50719222-f8e15d00-105e-11e9-9e3f-ebd691bcf11c.png)

I'd thought about adding it as an option to the `section` command, but since it's computed, a template would have to do a bunch of unnecessary backtracking and reparsing.

**Comment by kainjow** [comment]
Feel free to create a PR if you have working code.

**Comment by kainjow** [comment]
I went ahead and added this since it was pretty straightforward.

**Comment by Wevah** [comment]
Thanks! (Though I secretly wanted my name in the commits…)

One nit: The `value` property should probably be `copy` insteady of just `rewrite`.

**Comment by Wevah** [comment]
Actually, I'll add a defaults key for that and submit a PR.
