### ISSUE TITLE
Templates: couple bytes to `entry` command

### ISSUE THREAD

**Issue by bvandergiessen** [ridiculousfish/HexFiend#178]
In [a previous issue](https://github.com/ridiculousfish/HexFiend/issues/146#issuecomment-450268573),  the `entry` command is introduced, to enter a sort of comment in a binary template, like

```tcl
entry "channel" $channel
```

This answers a number of feature requests about displaying custom values instead of the values of the raw bytes. I think it is a very useful addition. But unfortunately the entry doesn't correspond to any bytes from the file at all - in fact it plays the role of a _comment_. As a further improvement, it would be great if the `entry` could be made to correspond to bytes from the file, so you'd be able to display _information relevant to the bytes_ in any desired way.

As one example, if there's a 4-byte CRC sum, the most relevant information is not its actual value, but whether it checks out. Thus, you'd like to display
 > CRC32     Correct

and when the user selects this, the four raw bytes in the file view are highlighted.

Could the `entry` command be changed to do this? The command has not been shown in documentation yet, so a slight backward incompatibility might not be a huge problem. If the syntax is changed to

```tcl
entry n label value
```

where `n` is the number of raw bytes to use (allowed to be 0), then we have flexibility and can write code like
```tcl
set chunk_crc [uint32]
move -4
if {[chksm $chunk_type$chunk_data] == $chunk_crc} {
	entry 4 CRC32 Correct
} else {
	entry 4 CRC32 FAILED
}
```

Another example: a one-byte numerical language code, where you'd like the template view to show the interpretation (i.e. what language it actually means) rather than the raw byte value. With `entry` in its current form, you can add an extra line to the template view that says "the line just above means it's Japanese", but that looks clumsier than putting it all in one item that corresponds to that byte.

**Comment by Kalli1964** [comment]
I would prefer to add also the position of the file pointer to the command, to reduce the need of `move -x` commands. With the introduction of the entry command I could remove some move commands, which seems to speed up some things (and looks nicer). So maybe a solution could be `entry "channel" $channel $len $pos` where len and pos are optional.

**Comment by bvandergiessen** [comment]
I think `pos` would then have to be optional - for me at least, the absolute position is something I avoid as much as possible.

In adherence to the existing syntax of the commands `bytes`, `hex`, `ascii` and `utf16`, I think the order of the arguments should be number-of-bytes, label, value. The position would then come at the end, because it's optional. It might be added to those four other commands as well.

**Comment by kainjow** [comment]
The point originally of `entry` was for arbitrary data not associated with any offset. For example if you read compressed data and wanted to display fields from that. I think we can have an offset and length both be optional, but I prefer optional at the end. How about:

```tcl
entry label value [len [position]]
```

If position is not specified, then the current offset is used. This should then handle all mentioned scenarios.

**Comment by kainjow** [comment]
Another complication: if the length is provided, should the file position move forward? Or should it stay the same? Possibly could be an optional argument "-move".

**Comment by kainjow** [comment]
Added the length and offset parameters in cf5e9c1c425b49b3ffac32f0fcb0638d3b570556.

**Comment by bvandergiessen** [comment]
Thanks, I'll try it out.

> Another complication: if the length is provided, should the file position move forward? Or should it stay the same? Possibly could be an optional argument `-move`.

This is a valid point, but I'd like to point out that it is a matter for _all_ type commands. If we have

```tcl
set x [uint32]
```

should the file position move forward by 4 bytes? Perhaps we intend to look at the data and then decide how to label it in the template view - so the cursor might as well stay put. But on the other hand, we might want to read a number of consecutive uint32 values first, and in that case it's useful if the command moves the position forward.

It would be good if this can be specified with an option on all of the type commands, for example `-s` (alternative form `--stationary`), with moving forward as the default.

You could also choose to do it the other way around - with an option to move forward - but there is a risk that the syntax is becoming a bit confusing if the default for `uint32` is moving, but not for `entry`, or moving for `uint32 label` but not  for `uint32`. (Putting `len` at the end of the `entry` command and at the start of `hex` etc. feels slightly inconsequent, too, but if `entry` was really not intended to label bytes, I understand it.)
