### ISSUE TITLE
ULEB128 Not displaying as expected in data inspector

### ISSUE THREAD

**Issue by Wikiemol** [ridiculousfish/HexFiend#180]
Steps to reproduce:

1. Create a new file
2. Insert 80 80 80 80 80 01
3. Select the inserted bytes and view as ULEB128 in the data inspector

The expected result is 34359738368, but the data inspector reads 8. 

In the [logic](https://github.com/ridiculousfish/HexFiend/blob/fe55548434c9ac30622a5dee404255654f112ddd/app/sources/DataInspectorRepresenter.m#L566), shifting by a value that is equal or greater than the width of the type of the left operand of the shift operator is undefined behavior. Casting the left operand to uint64_t fixes this. 

I suspect there is a similar issue with SLEB128.

**Comment by kainjow** [comment]
80808080807F doesn't work either (should be -34359738368). I used the function here to write out test data to verify the fixes: https://github.com/llvm-mirror/llvm/blob/993ef0ca960f8ffd107c33bfbf1fd603bcf5c66c/include/llvm/Support/LEB128.h
