### ISSUE TITLE
Toggling the Line Numbers view inconsistently changes the size of the window

### ISSUE THREAD

**Issue by roryokane** [ridiculousfish/HexFiend#182]
Toggling the Views > Line Numbers option twice should have no effect, but in fact it shrinks the window by one column.

To demonstrate, I start with 16 bytes per column with Line Numbers on:

<img width="925" alt="16 bytes per column, Line Numbers on" src="https://user-images.githubusercontent.com/79168/51423566-477b1500-1b90-11e9-98c3-c5d3b7d1a89c.png">

I choose the menu item Views > Line Numbers, turning line numbers off. The window gains one extra column, presumably aiming to keep the graphical window approximately the same width. Personally, I would prefer that the window shrink so that the number of bytes per column stays the same, but I can see the argument for the other behavior.

<img width="905" alt="17 bytes per column, Line Numbers off" src="https://user-images.githubusercontent.com/79168/51423592-9628af00-1b90-11e9-8db6-ff7a365fd0ef.png">

Then I turn Line Numbers on again. The window loses *two* columns to make space for the line numbers. So the window has changed from 16 bytes wide to 15 bytes wide due to the setting round-trip.

<img width="880" alt="15 bytes per column, Line Numbers on" src="https://user-images.githubusercontent.com/79168/51423610-e6077600-1b90-11e9-8813-a385b5d084fd.png">

If the window is to gain or lose columns when Line Numbers is turned on or off (which, I again, I would prefer not happen), then the number of columns gained and lost should be equal. I have no preference whether that number is one or two.

See also https://github.com/ridiculousfish/HexFiend/issues/121, which requests that the window automatically change size when the Binary Templates view is toggled. I haven’t tried the 2.11 beta, but I hope [the fix](https://github.com/ridiculousfish/HexFiend/commit/f80715ff1afffb5589949e1e2de8ba1365bcbcb1) doesn’t have this same inconsistency problem.

**Comment by kainjow** [comment]
It should be fixed with the fix for the issue you linked in f80715ff1afffb5589949e1e2de8ba1365bcbcb1

Can you test with 2.11?

**Comment by roryokane** [comment]
You’re right – after downloading and trying the steps in Hex Fiend v2.11.0b5, the bug seems to be fixed. In the beta version, when Line Numbers is toggled, the window resizes so that the same number of columns are always displayed.

Downloading and running the beta was easier than I thought – I should do that first next time.
