### ISSUE TITLE
Unable to paste string containing Unicode into text

### ISSUE THREAD

**Issue by wesinator** [ridiculousfish/HexFiend#186]
**To reproduce:**
 - Copy string containing Unicode zero-width char, "`examp‌le.com`" (`examp\U+200Cle.com`)
 - Paste into text view

Nothing is pasted, paste does nothing

**Expected:** pastes the raw UTF-8 string `examp\xE2\x80\x8Cle.com`

**Comment by kainjow** [comment]
Text will only successfully get pasted if it can be converted to the current encoding. In Text Encoding menu you can choose UTF-8 from Other and then it should paste correctly.

**Comment by wesinator** [comment]
Ah, ok thanks.
