### ISSUE TITLE
[Feature request] bit offsets for binary templates

### ISSUE THREAD

**Issue by kumowoon1025** [ridiculousfish/HexFiend#188]
There's no way to deal with anything that's not byte aligned with "binary" templates, unless I'm missing something. It would be useful for reading files that contain bitstreams, and also raw devices.

**Comment by kainjow** [comment]
Could you provide an example of how you'd use it, maybe a specific data format?

The [expr](https://www.tcl.tk/man/tcl8.6/TclCmd/expr.htm) Tcl command has bitwise operator support, so it could be done with that and Hex Fiend's `uint8` command.

This was also mentioned here: 
https://github.com/ridiculousfish/HexFiend/issues/89#issuecomment-399803545

**Comment by kainjow** [comment]
Since HF's templates were inspired by WinHex, in their [manual](http://www.x-ways.net/winhex/manual.pdf) they describe a "uint_flex" command:

> A special variable type supported by templates is `uint_flex`. This type allows to compose an unsigned integer value from various individual bits within a 32-bit (4-byte) range in an arbitrary order and is even more flexible than a so-called bit field in the C programming language.
> 
> uint_flex requires an additional parameter string in inverted commas that specifies exactly which bits are used in which order, separated by commas. The bit listed first becomes the most significant bit (high value bit) in the resulting integer, and it is not interpreted as a + or - indicator. The bit listed last becomes the least significant bit in the resulting integer.
>
> The bits are counted starting with 0. Bit 0 is the bit that is the least significant bit of the 1st byte. Bit 31 is the most significant bit of the fourth byte. Thus, the definition is based on little-endian philosophy.
>
> For example,
`uint_flex "15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0" "Standard 16-bit integer"`
is exactly the same as `uint16`, the common unsigned 16-bit integer variable.
> 
> `uint_flex "31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,
11,10,9,8,7,6,5,4,3,2,1,0" "Standard 32-bit integer"`
is exactly the same as `uint32`, the common unsigned 32-bit integer variable.
>
> The benefit of `uint_flex`, though, is that the number, the position, and the usage order of all bits can be chosen arbitrarily. For example,
`uint_flex "7,15,23,31" "An unusual 4-bit integer"`
composes a 4-bit integer out of the respective most significant bits of each of the four bytes involved. If these four bytes happen to be
F0 A0 0F 0A =
11110000 10100000 00001111 00001010,
bit 7 is 1, bit 15 is 1, bit 23 is 0, and bit 31 is 0.
So the resulting uint_flex is 1100 = 1*8 + 1*4 + 0*2 + 0*1 = 12.

maybe something like this would work?

**Comment by kainjow** [comment]
I think instead of a single type that reads only 4 bytes, this could be implemented with 8, 16, 32, and 64 bit size commands. I also think "bits" might be better name suffix. For example `uint8_bits`.

**Comment by kumowoon1025** [comment]
> Could you provide an example of how you'd use it, maybe a specific data format?

Sure, if you were to parse the encoded bitstream of media files, there's not so much a file structure, but a stream format, which usually needs to be decoded an arbitrary number of bits at a time.

Here's the start of a core frame header for DTS as an example.
```
....7FFE 8001FC3C
7DB27702 0D3A0009
EF7BDEDE F7BD8000
```

`7FFE8001` is the sync word. Then there are 
```
FTYPE(1)
SHORT(5)
CPF(1)
NBLKS(7)
FSIZE(14)
...
```
The sizes are in bits.
Yes,  I could probably read a uint8 then and mask and shift to get the component bits.
(0xFC & 0x80)  >> 7 would get me 1 for FTYPE
(0xFC & 0x7C) >> 2 for 31 as SHORT
(0xFC & 0x02) >> 1 is CPF...
and it's almost feasible till here where I need to read 7 bits of NBLKS across two bytes. It is still doable, I could "carry over" the bit, go back and read two bytes this time but at this point it's like I'm trying to use a tape measure when what I really need is a set of feeler gauges.

More realistically, I would keep a secondary buffer and offset on my own, and I realize any implementation of a feature like this would have to involve a similar mechanism, but I found myself wishing this was a thing often enough and wondered if I was alone. 

As far as how one would use such a feature, I have to admit I'm not entirely sure what the best way would be, it shouldn't be the "default" for sure, maybe a command to read n bytes and initialize a sort of sub-context to read them into a struct with bit fields? something like
<pre>
<code>unpack_bytes <i>size</i> {
    bit <i>count label</i>
    ...
}</code>
</pre>

**Comment by kainjow** [comment]
I added an experimental uintX_bits command based on uint_flex described above. I also released a new beta for testing: https://github.com/ridiculousfish/HexFiend/releases

The command works the same as above but has 4 variants: `uint8_bits`, `uint16_bits`, `uint32_bits`, and `uint64_bits` for reading respective number of bytes.

The second argument is a string with the bit offsets separated by commas. The command only returns a single bitwise or'd value from the bits, starting from left to right. The integer is read via the current endian, so to read from right to left in bits you must read as big endian. The last argument is the label, same as other type commands.

So for your example, the fields could be read like so:

```tcl
big_endian
uint32_bits "31" "FTYPE"
move -4
uint32_bits "30,29,28,27,26" "SHORT"
move -4
uint32_bits "25" "CPF"
move -4
uint32_bits "24,23,22,21,20,19,18" "NBLKS"
move -4
uint32_bits "17,16,15,14,13,12,11,10,9,8,7,6,5,4" "FSIZE"
```

**Comment by kainjow** [comment]
However, looking at the larger example of DTS here: http://stnsoft.com/DVD/dtshdr.html I can see how this would be kind of clunky to work with, especially since in that case it's using 6 bytes and nothing is on byte boundaries. Your example could be another way to make it work. For example if a "bits" command was added it could keep track of the current bit offset and allow reading n number of bits for more easily handling of a stream of bits back to back:

```tcl
bits 1 "ftype"
bits 5 "short"
bits 1 "cpf"
bits 7 "nblks"
bits 14 "fsize"
bits 6 "amode"
bits 4 "sfreq"
bits 5 "rate"
bits 1 "mix"
bits 1 "dynf"
bits 1 "timef"
bits 1 "auxf"
bits 1 "hdcd"
```

It could keep track of the bit offset, with any other read command resetting the bit offset back to 0.

I think both formats would be useful for different scenarios.

**Comment by Kalli1964** [comment]
Kaitai Struct uses the second approach: http://doc.kaitai.io/user_guide.html#_bit_sized_integers
The parsing is fixed from left to right, which makes sense for bitstreams. In my opinion, your second approach looks nicer and the template is easier to write and to maintain (especially, if you forget a bit).

**Comment by ericboxer** [comment]
I came across a use case where I need to be able to read some data bits. Is this something that is still being worked on?

**Comment by kainjow** [comment]
> I came across a use case where I need to be able to read some data bits. Is this something that is still being worked on?

2.12.0 has the *_bits functions, and I'd still like to do the other implementation I suggested above.

**Comment by kumowoon1025** [comment]
Thanks, the flex bits command saves a lot of tedious math needing to be copy pasted in every template. I had a hard time figuring out the bit ordering for the multiple byte variants, though, uint16_bits numbering 7~0 then 15~8 was impossible to figure out without reading the source. After seeing how it's implemented, it seems somewhat natural, but I think adding the logic to treat those bytes as a continuous sequence of bits would be worthwhile.

**Comment by kumowoon1025** [comment]
I think as a feature this can be considered implemented, maybe could see an enhancement in the future, but once you get used to the bit and byte ordering, it is a pretty solid answer to what was missing.
