### ISSUE TITLE
Integrate Kaitai with HexFiend for Templates

### ISSUE THREAD

**Issue by halsten** [ridiculousfish/HexFiend#189]
Any chance you can integrate [Kaitai](http://kaitai.io/) to improve on template writing and also the extensibility of HexFiend. It's a nice utility that I use a lot, but this Tcl choice of yours is rather interesting. You know Python also ships with macOS and so does a lot of other things too. Would be nice to see this added to the tool.

--halsten

**Comment by kainjow** [comment]
It's been brought up before, see https://github.com/ridiculousfish/HexFiend/issues/89#issuecomment-354649108

It's also GPL3.

**Comment by kainjow** [comment]
Everyone’s going to have their favorite language. What made Tcl stand out was it’s simple syntax. A lot of templates don’t look like source code. It also treats everything as a string. Python would require conversions, and doesn’t appear to support 64-bit unsigned integers out of the box. Also I’m unsure if the built-in Python in macOS can be directly embedded.

Saying all that, if you want to add support for a new language that’s already part of the Mac I wouldn’t be applaud to it. The code is also designed to separate the template language implementation from the language itself.

**Comment by karstenBriksoft** [comment]
Kaitai defines a Yaml based structure for describing binary data. There's also a kaitai structure compiler that converts the structures into code that can be integrated with other software that needs to parse the particular kinds of data.
That last part is not very interesting for HexFiend, but the first part is. I've created a Yaml decoder (based on libYaml, which can be installed via homebrew: brew install libyaml). If present, the Kaitai TemplateController will be used for .ksy files in the template folder.
It's not fully working yet, but it's a nice start (see my fork at: https://github.com/karstenBriksoft/HexFiend)

**Comment by kainjow** [comment]
While I find your work commendable, I wonder if instead of rewriting all that logic, it'd be better to add support to HexFiend to somehow support one of the languages that Kaitai already supports, either through IPC or direct scripting. Then there would be no duplicate logic, just bindings to HF. I haven't looked to see if this would even be doable though.
