### ISSUE TITLE
Scroll window rather than fixed.

### ISSUE THREAD

**Issue by thesamprice** [ridiculousfish/HexFiend#199]
When inspecting packets of fixed sizes it would be useful to have each packet in a row, so I can scroll down and look at all the fields.

Currently I can only look at packets of small sizes, or I chunk the headers off of my packets to view them per row.

If the left, and right and bars were converted to scroll windows, and users allowed to specify the number of columns, this would allow for identifying of trends across columns.

**Comment by kainjow** [comment]
Since 2.11.0 you can use a custom byte grouping. Does this help?

**Comment by kainjow** [comment]
Closing due to lack of response.
