### ISSUE TITLE
Binary template panel width option seems broken

### ISSUE THREAD

**Issue by wader** [ridiculousfish/HexFiend#201]
Hello! the binary template width option does not work for me. Think i managed to change it once but not sure how i did it.

**Comment by wader** [comment]
Version 2.12 (1550028051)

**Comment by wader** [comment]
Ohh now i figured it out... have to press enter in the input field 😄

**Comment by kainjow** [comment]
yeah, it's clunky. I'd like to redo the entire layout some day to use Autolayout but that's another big job.
