### ISSUE TITLE
Shift + click selections not working in 2.12

### ISSUE THREAD

**Issue by ibreakifix** [ridiculousfish/HexFiend#202]
It looks like Hex Fiend 2.12 broke the ability to shift + click to select between the cursor and pointer. When attempting to perform a selection, the cursor jumps to the new location without anything being selected.

I am assuming that this is a bug and not the result of the functionality being intentionally removed.

**Comment by kainjow** [comment]
Yes definitely an accident. I've fixed it. Thanks!
