### ISSUE TITLE
HFRepresenter's view is untyped, making it relatively difficult to use from Swift

### ISSUE THREAD

**Issue by jverkoey** [ridiculousfish/HexFiend#206]
The `view` method on HFRepresenter is typed as an id:

https://github.com/ridiculousfish/HexFiend/blob/104c9f740ca113628e5d027102bc8d97707724a6/framework/sources/HFRepresenter.h#L45

Swift code then need to look like this (in Cocoa):

```swift
let view = (layout.view() as! NSView)
```

Would it be possible to add type information to the view API? It may also improve Swift readability if the API were declared as a property.

**Comment by kainjow** [comment]
Added. Although it's using an `HFView` preprocessor definition. I think Swift should be able to pick that up though.
