### ISSUE TITLE
Add Spaces to Copied Hex

### ISSUE THREAD

**Issue by utkonos** [ridiculousfish/HexFiend#208]
One of the most frequent use cases I have for a hex editor is to find opcodes that I've identified in a debugger. I then paste them into YARA rules. For readability in YARA, it's good practice to add spaces between bytes like so:

```
$a = { 01 DB 75 07 8B }
```

Can an optional feature be added to the preferences that adds spaces between bytes when copying to the clipboard?

I know this small snippet is easy to add spaces to, but for longer opcodes, having spaces added automagically would be a time saver.

**Comment by kainjow** [comment]
It'd should be fairly easy to add a Preference to turn on this behavior for all copying.

**Comment by kainjow** [comment]
So it formats the text based on the active Byte Grouping value in under the Views menu. I suppose we could add a preference for this to use the current one, or override it. What is your current Byte Grouping value?

**Comment by utkonos** [comment]
I have byte grouping set to 4.

**Comment by utkonos** [comment]
Most everything I do is PE32 or PE32+ so, 4 works well for dword/qword.

**Comment by Siggi88** [comment]
An old version of Hex Fiend actually put a space between each byte in hex.  The latest version uses the byte grouping setting in View -> Byte Grouping.  I'm actually looking for a way to not add spaces at all to copied hex though, without having to set View -> Byte Grouping to "None."  It's kind of a pain to have to paste it in a text editor and then replace all spaces to blank and then recopy it when I needed the hex without spaces.

**Comment by Siggi88** [comment]
It would be nice to have copying and viewing be separate settings rather than together as one.

**Comment by utkonos** [comment]
Since the grouping in copy is controlled by the byte grouping setting in the View menu, I think the easiest setting would be an additional setting called "Byte Grouping on Copy". The settings for this would mirror the options in Byte Grouping except that there would be one more option "Same as Display".

**Comment by kainjow** [comment]
@utkonos yep I think that is the best approach. I'll look into it.

**Comment by kainjow** [comment]
I kept it simple for now and added this to preferences:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/271035/73127592-77b17c80-3f77-11ea-958f-07b308582266.png">

**Comment by utkonos** [comment]
Very nice. Thanks!

**Comment by kumowoon1025** [comment]
A bit late here, and it's a really minor issue, but maybe the default should be no spaces? I don't know what would be the expected behavior for the majority of people, so that is a big maybe.

I had a hard time debugging an EDID parser that was acting completely out of order, and it turned out it expected continuous hex digits no spaces. It even had an option to "add spaces between bytes" so I assumed it would handle input in that form appropriately as well, so maybe it's the parser that's out of order, but I'm wondering how byte grouping with spaces is usually handled in a "typical" situation where someone might copy a bunch of hex bytes from the view and paste it somewhere.

**Comment by utkonos** [comment]
> A bit late here, and it's a really minor issue, but maybe the default should be no spaces? I don't know what would be the expected behavior for the majority of people, so that is a big maybe.
> 
> I had a hard time debugging an EDID parser that was acting completely out of order, and it turned out it expected continuous hex digits no spaces. It even had an option to "add spaces between bytes" so I assumed it would handle input in that form appropriately as well, so maybe it's the parser that's out of order, but I'm wondering how byte grouping with spaces is usually handled in a "typical" situation where someone might copy a bunch of hex bytes from the view and paste it somewhere.

The current default is the exact same behavior as the hex editor had before this feature was added. I think it's a reasonable default.

**Comment by kumowoon1025** [comment]
> The current default is the exact same behavior as the hex editor had before this feature was added. I think it's a reasonable default.

Ohh, gotcha. True, now that you tell me that, the decision does make complete sense. But it's just that I didn't know this feature existed and did `pbpaste | tr -d ' ' | pbcopy` every time, so if the default was changed to no spaces when this feature was added...

I guess I still would have been none the wiser ._.

But supposing I _had_ noticed, I'm just saying it would have been a surprise, but a pleasant one.

And this is a separate issue but I really feel like the dropdown option for single byte grouping should say "one byte" or  something, not "one space." As it is right now it doesn't immediately click for me as to what that means. (I was initially like of course it's one space why would anyone ever want two??)
