### ISSUE TITLE
Support file grammars

### ISSUE THREAD

**Issue by alexchandel** [ridiculousfish/HexFiend#209]
A couple hex editors support "grammars" (similar to Wireshark's dissectors) which allow the GUI to display a parse tree of the hex file.  "Synalyze It" in particular has a decent repository of grammars [here](http://www.synalysis.net/formats.xml).  Additionally there are many [binary parsing frameworks](https://github.com/dloss/binary-parsing) with some variant of a file grammar.

It would be nice to have some file parsing abilities in Hex Fiend.

**Comment by kainjow** [comment]
Like this? https://github.com/ridiculousfish/HexFiend/blob/master/templates/Tutorial.md

**Comment by kainjow** [comment]
The releases page shows what's been added to each version regarding this feature: https://github.com/ridiculousfish/HexFiend/releases
