### ISSUE TITLE
[Feature Requests] Info window for selection highlights

### ISSUE THREAD

**Issue by karamellpelle** [ridiculousfish/HexFiend#211]
I've been trying to reverse engineer a binary file format. During this process, I take a lot of notes on regular paper. It would be very helpful to add notes to the colored selections you highlight in HexFiend. The text will be shown while hoovering the mouse above the highlight. As a reference, [Ableton has the functionality to add info text](https://www.youtube.com/watch?v=DS81szjORWA) (i.e. taking notes) to much of your work. This is a form of GUI tooltip but better: by having a text box you will not be annoyed by pop up text, the text will be shown immediately when hoovering above a highlight, and you can create notes with line shifts.

BTW, thanks for this amazing software!

**Comment by kainjow** [comment]
The bookmarks feature is pretty similar to this, but it just gives each bookmark a name of 1, 2, etc. We could change it so when you add a bookmark, you are prompted to change the default name. This would probably be pretty simple to do. What do you think?

**Comment by karamellpelle** [comment]
Hi! My initial though was the ability to put custom text into the "Callout" balloon of bookmarks. This will be very annoying. Another solution would be to use a [tooltip](https://en.wikipedia.org/wiki/Tooltip) when hoovered over a bookmark/selection. This will be annoying. A tooltip typically have a wait time before it's shown. A tooltip will hide the content below, also when unintentionally hoovering over bookmarks/selections. Another solution could be to use a status bar at the bottom, but this does not provide space for longer comments and line shifts.

I really like the way Ableton Live does. By having a dedicated box in the GUI window (with the ability to toggle the visibility of this box, of course) you will not hide content below. You will not be annoyed. You can have comments with line shifts. And you have a place to type in your notes. In Ableton Live you just right click and select "Edit info text" in the popup menu. In HexFiend you could do the same by right clicking a highlighted selection.

**Comment by kainjow** [comment]
Can you provide a screenshot from Ableton Live of what you're referring to? The problem with implementing a note taking feature into HF it'll always be inferior to any other dedicated note taking app.

Another idea for the bookmarks is to allow labeling them, but don't show the label inline, just in the menu.

**Comment by karamellpelle** [comment]
The idea was the ability to put notes at specific locations of the binary file. Here is an image of the Info View in Ableton (left bottom, outlined in red): [Info-View.jpg](https://uploads-ssl.webflow.com/58b8f98a097974ea1e38cb88/5a8108a5d2e04c0001f58ecd_Ableton-Live-10-Info-View.jpg). Here is [another image](https://www.ableton.com/en/manual/first-steps/#2-1-1-using-the-info-view-and-index) from the Ableton Manual. The Info View changes content based on cursor location, and you can edit/write notes when hoovering over locations of your interest.

You decide what to do; this was an idea of a new feature.
