### ISSUE TITLE
Custom font color does not save ?

### ISSUE THREAD

**Issue by wesinator** [ridiculousfish/HexFiend#215]
Font -> Custom Font 

The dialog isn't clear how the font setting is changed/saved.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/5124946/71316716-af8e4700-2442-11ea-961a-8a74b128e8a9.png">

how do I change the color, or is it broken ? 

Thanks,

**Comment by kainjow** [comment]
Changing the color isn't supported here. Hex Fiend will use default OS colors.

Can you go into more details on what you're trying to do?

**Comment by wesinator** [comment]
> Changing the color isn't supported here. Hex Fiend will use default OS colors.
> 
> Can you go into more details on what you're trying to do?

I'm trying to change the font color of the data in the hex view 
If it isn't supported, why does it show a font dialog with a color picker ?

**Comment by kainjow** [comment]
It shows the system's font panel and it appears that's the default view.

However it appears there may be a way to customize this via https://developer.apple.com/documentation/appkit/nsfontchanging/3005181-validmodesforfontpanel?language=objc - I'll need to do some experimenting.

**Comment by kainjow** [comment]
I figured out a way to make the font panel only allow customizing the font face, to reduce confusion.

Currently HF only allows customizing the background color of a selection via "highlighting". You can access this from the context menu
