### ISSUE TITLE
Translating values in templates

### ISSUE THREAD

**Issue by ejm554** [ridiculousfish/HexFiend#218]
_This is a question seeking support. Hopefully, I'm posting in an acceptable place. If not, please tell me where it belongs and accept my apologies. :-)_

I'm a Hex editor and Tcl noob, but I've been trying my hand at creating a template for HexFiend to decipher Microsoft Access MDB files (a.k.a. Jet databases).

I've made a line in the template that returns the version of one of these files: `uint32 "Jet Version"`. It will return a value of either 0, 1, 2, or 0x103. 

I'd like to know if I can translate one of those values into an _alternative value_ that is more meaningful to me. For example:

Name Column | Current Value | Alternative Value
------------ | ------------- | -------------
Jet Version | 1 | Access 2000, 2002/2003 (Jet 4)

OR

![HexFiend-Access](https://user-images.githubusercontent.com/26723535/71561744-0f3ab280-2a40-11ea-9295-af7dd09cc986.jpg)

**Is this possible?**

**Comment by wader** [comment]
Don't think there is any builtin function to do it. This is what i've done https://github.com/ridiculousfish/HexFiend/blob/master/templates/Audio/FLAC.tcl#L62 create a dict for mapping value to string.

**Comment by kainjow** [comment]
You'll need to use the "entry" command to add an artificial item. The dictionary is a nice way to do it. You can also throw together an if statement, something like:

```tcl
set version [uint32]
move -4
set altname "Unknown"
if {$version == 0} {
    set altname "Access 2000, 2002/2003 (Jet 4)"
} elseif {$version == 1} {
    set altname "One"
}
entry "Jet Version" $altname
```

**Comment by ejm554** [comment]
I got close with the if statement, but having issues with how text is selected. Can you describe the dictionary option a bit more, but for a beginner? I had difficulty understanding the linked example.

**Comment by lemnet** [comment]
That should work : 
```
proc getaltvalue {jetversion} {
	switch $jetversion {
		0 {return "Access 2000"} 
		1 {return "Other version"}
		default {return "Unknow Version"}
	}
}
[...]
set jetversion uint32
entry "Jet Version" [getaltvalue $jetversion]
[...]
```
