### ISSUE TITLE
2.11.0 no updates found

### ISSUE THREAD

**Issue by wesinator** [ridiculousfish/HexFiend#221]
macOS 10.14.6

2.12.0 update is not offered 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/5124946/72380766-17534d00-36e4-11ea-8742-cce3182e6ffb.png">

**Comment by kainjow** [comment]
Yeah I need to update the appcast file.

**Comment by alvarnell** [comment]
Been over three weeks since release and almost a week since acknowledging this issue. In case you believe the appcast file has been updated, it still has not.
