### ISSUE TITLE
Memory leak on search replace operation on binary files

### ISSUE THREAD

**Issue by S3D-Nikhil** [ridiculousfish/HexFiend#222]
Do a text/hex replace all on a byte that is repeated several times in a binary file, preferably 5-10 MB or more in size. This will lead to the memory used to jump from 20 MB to 8+ GB and is not cleaned up when the operation is complete. Sometimes it will even lead to a crash on systems with 8GB or less RAM. 
![HexFiendMemory](https://user-images.githubusercontent.com/39490757/72997168-efda3f80-3dc9-11ea-9fd3-15892250a3f4.png)

**Comment by kainjow** [comment]
yep it's an old known issue. See #78
