### ISSUE TITLE
Handle on drive even after all files open from it are closed

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#233]
# To reproduce
1. Open an ISO
2. Open a file from that ISO in HexFiend
3. Close the file
4. Try to eject the ISO

# Expected
- Should eject OK

# Actual
- Cannot eject because HexFiend still has a handle on it

**Comment by kainjow** [comment]
First time using the Debug Memory Graph in Xcode. Pretty useful and made this much easier than before with Instruments: https://developer.apple.com/documentation/xcode/improving_your_app_s_performance/reducing_your_app_s_memory_use/gathering_information_about_memory_use?language=objc

**Comment by gingerbeardman** [comment]
Thanks so much! I had thought twice about filing this issue. Glad I did!
