### ISSUE TITLE
Difficult to read text in dark mode

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#235]
Having seen the screenshot at: https://github.com/ridiculousfish/HexFiend/issues/162

I see a different, worse Dark Mode.

Any thoughts?

![Screen shot 2020-03-16 at 22 36 34](https://user-images.githubusercontent.com/49612/76805406-9e9d6980-67d6-11ea-95e2-382bf772a7cc.png)

**Comment by tomtastic** [comment]
I dont understand why there's an option called 'Color Bytes', when they're actually shades of grey.

**Comment by gingerbeardman** [comment]
I believe I also had macOS Night Shift activated, which seems to have been contributing to the issue.

**Comment by kainjow** [comment]
Looks like you have Color Bytes turned on, and maybe a highlighted color applied?

**Comment by kainjow** [comment]
I fixed Color Bytes for dark mode:

<img width="519" alt="Screen Shot 2020-03-21 at 12 21 09 PM" src="https://user-images.githubusercontent.com/271035/77234905-1bca3500-6b6f-11ea-870c-3f13ca9c04cf.png">

**Comment by gingerbeardman** [comment]
Thanks!
