### ISSUE TITLE
Malformed UTF-8 + UTF-16LE = instacrash

### ISSUE THREAD

**Issue by nk9** [ridiculousfish/HexFiend#241]
I was asking for trouble by opening [this file](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt) of intentionally malformed UTF-8 in Hex Fiend, but everything was going fine. Until…

Steps:
1. Turn on View > Color Bytes
2. Set Text Encoding to UTF-16 LE or BE
3. Open the file

Of course, Hex Fiend kindly remembers the last file I opened and my settings. So it is now crashes immediately on launch with `AEGetDescData of non-desc type 'reco' not a good idea` in the console:

Moving the file didn't solve the problem, so I had to take the rather heavy-handed approach of:

```
$ rm -rf ~/Library/Containers/com.ridiculousfish.HexFiend/Data/Library/Saved\ Application\ State/com.ridiculousfish.HexFiend.savedState
```

**Comment by kainjow** [comment]
Looks like you’re using the App Store version, which is out of date. Does the crash reproduce with the latest release posted here on GitHub? If so, can you post the crash report? It should be in ~/Library/Logs/DiagnosticReports

**Comment by kumowoon1025** [comment]
Can't reproduce with current build... Also AE usually has something to do with Apple Events, and in turn AppleScript, looking it up in the Cocoa docs, 'reco' is the raw value for `typeAERecord` of enum `DescType`, something to do with recording system events (Like the record button in Script Editor or  "watch me do" in automator)

I doubt it has something to do with the app, but if none of this sounds like it might be the cause, does this happen on more than one machine/login? And also, on a more recent release, as has been suggested.

**Comment by nk9** [comment]
My apologies for not including the version. Indeed, I was using the App Store's version of 2.8. When I follow the steps on 2.12, the crash doesn't happen. That being the case, I'll close this now.
