### ISSUE TITLE
Text Encoding for Spanish

### ISSUE THREAD

**Issue by ptoche** [ridiculousfish/HexFiend#247]
I'm trying to read a Spanish dictionary (mobi converted to html with calibre's KindleUnpack plugin), but can't seem to find the correct text encoding. I have tried every option listed and none display the «ñ» in « Español». Any ideas? Thanks.

Edit: The html file has a header stating 'charset=utf-8'.

**Comment by gingerbeardman** [comment]
It's possible that the contents of the file are simply wrong.

Can you share the file (or part of it)?

**Comment by ptoche** [comment]
Hi gingerbeardman! 

Thanks for your help.

Below are a few lines from the top of the (html) file. I was assuming that the `charset=utf-8` was a hint as to the underlying type of characters, but maybe not. The file was produced from a Kindle Amazon dictionary (free sample) in `azw` format converted to `html` by the KindleUnpack plugin of calibre. The resulting file is very l, so below is just an extract.

I'm on MacOS Catalina 10.15.4. 

Below are a few lines from the top of the file:
    <html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><guide><reference title="Contenido" type="toc"  filepos=0000000166 /><reference title="Comenzando" type="text"  filepos=0000063413 /></guide></head><body><a id="filepos166" /><h3 height="20%" width="0">&Iacute;ndice</h3><div height="1em"></div> <div > <ul> <li><a  href="#filepos652" >Pre&aacute;mbulo</a></li> <li><a  href="#filepos13040" >La vigesimotercera edici&oacute;n del Diccionario de la Real Academia Española</a></li> <li><a  href="#filepos30471" >Advertencias</a></li> <li><a  href="#filepos44276" >Abreviaturas y signos empleados</a></li> <li><a  href="#filepos67366265" >Ap&eacute;ndice. Modelos de conjugaci&oacute;n</a></li> </ul> </div>  <mbp:pagebreak/><a id="filepos652" /><h3 height="20%" width="0">Pre&aacute;mbulo</h3><div height="1em"></div> <div > <p height="1em" width="0">Al contemplar, ahora con tres siglos de distancia, los jalones que se sucedieron en la fundación de la Real Academia Española y el alumbramiento de su espléndida obra primera, llama la atención una peculiar circunstancia que es la reiteración, se diría que casi cabalística, aunque indudablemente casual, del número trece en los intervalos de aquellos hitos. Iniciadas las tareas de la corporación en el decimotercer año del siglo XVIII, fueron exactamente trece los años necesarios para dar a luz el primer tomo (1726) del que con el tiempo sería conocido como <a href="http://www.rae.es/recursos/diccionarios/diccionarios-anteriores-1726-1996" target="_blank"><em>Diccionario de autoridades</em></a> <span >&mdash;una</span> obra que está en la base de toda la lexicografía académica posterior, y por tanto también del diccionario que tiene el lector en sus <span >manos&mdash;</span> y otros trece los que transcurrieron hasta la culminación de la hazaña con la publicación en 1739 del sexto y último tomo.</p> 
    </body></html>

**Comment by wader** [comment]
It looks like UTF-8 encoding. But maybe what is confusing it that come characters are encoder using multiple bytes, for example é is ended using the bytes 0xc3 0xa9 you can see it in how "académica" i encoded. I guess it's hard to represent this in the ASCII view on the right in a resonable way, should it show the two bytes as "éé" or just one "é"? or like now, show what each byte would be as ASCII... but now sure the reason for the "?"

**Comment by kumowoon1025** [comment]
The variable-byte branch was mainly for supporting this kind of multi-byte encoding though it's a bit old

**Comment by ptoche** [comment]
Thanks for the feedback. Do you see it as a problem on my end? If you copy-paste the html code above into a text file and open it in hexfiend, do you get the same muddled display on your system?

**Comment by kainjow** [comment]
@wader is right. UTF-8 isn't well supported because HF has only supported fixed-byte encodings, but UTF-8 is variable. See #185
