### ISSUE TITLE
HexFiendling, "File Data, Multiple Views" fails on 10.9

### ISSUE THREAD

**Issue by ioquatix** [ridiculousfish/HexFiend#25]
Assertion failed: (success == __objc_yes), function generateGlyphs, file /Users/samuel/Documents/Programming/Applications/HexFiend/framework/sources/HFRepresenterStringEncodingTextView.m, line 114.

**Comment by kainjow** [comment]
I disabled the added code in 4a7085f and did not get the assert on 10.12.1. I think we can just leave the code here for now as it only runs if `CTFontGetGlyphsForCharacters()` fails, and that is what is checked in the assert.
