### ISSUE TITLE
Highlight color in hex panel is difficult to see

### ISSUE THREAD

**Issue by regisverdin** [ridiculousfish/HexFiend#256]
Love the tool! But when i highlight something in the right (ascii) panel, it's really hard to find the corresponding data in the left (hex) panel. The highlight color is currently gray in dark mode, and seems off gray in regular (daytime) mode. 

A more contrasting color here would be really helpful.

**Comment by gingerbeardman** [comment]
Let me know your thoughts regarding https://github.com/ridiculousfish/HexFiend/issues/235

**Comment by kainjow** [comment]
@regisverdin can you post a screenshot? It does sound like #235
