### ISSUE TITLE
Enhancement request: allow Find to be canceled

### ISSUE THREAD

**Issue by IvanExpert** [ridiculousfish/HexFiend#261]
When performing a Find on a very large file, it's really pretty fast, but it can still take several seconds or minutes. It would be nice to be able to cancel it.

**Comment by gingerbeardman** [comment]
You can click the cross

![Screen shot 2020-05-31 at 16 53 57](https://user-images.githubusercontent.com/49612/83356641-59152500-a35f-11ea-8216-9a32499955a1.png)

Not sure if there is a keyboard equivalent.

**Comment by KingSupernova31** [comment]
The cross has become more difficult to see in the newest version, may be worth updating the colors.

<img width="83" height="73" alt="Image" src="https://github.com/user-attachments/assets/a4cbf947-0c9b-4714-a210-c37000e64ace" />

**Comment by gingerbeardman** [comment]
I can't see the cross at all on 2.18.1 (1728795549) in light or dark mode.

<img width="255" height="97" alt="Image" src="https://github.com/user-attachments/assets/b8933d99-33ab-4a0b-a525-2123516c280b" />

**Comment by KingSupernova31** [comment]
Are you actually performing a search? The X only appears while the search is in progress. There should be a blue progress bar moving across the screen.

**Comment by gingerbeardman** [comment]
No I am not :) thanks for the hint
