### ISSUE TITLE
Template Pane can't be resized

### ISSUE THREAD

**Issue by inspier** [ridiculousfish/HexFiend#264]
From what I can tell the Template Pane remains a fixed size and can't be made wider, this poses a problem with fields that have longer names, you can of course resize the two columns within the pane, but the pane itself isn't able to be resized thus it cuts off some of one of the two columns when resizing them to be able to see the whole value of either. I am not sure whether this is something that could be fixed, but just curious.

**Comment by kumowoon1025** [comment]
It can be resized, though it’s not as elegant as we are used to with auto layout. You can specify the width in pixels in the preferences window, and it will be that size on layout (i.e. when you resize the window)

As an enhancement request, I would second this but as usual with all things UI in HexFiend, I cower away at the thought of working on it myself :/

**Comment by kainjow** [comment]
Yes that was added as a workaround. The issue is when you resize the window

**Comment by kumowoon1025** [comment]
Ah I didn't even think about that. My first thought would be to resize the template view, since in my experience I want to keep the "bytes per line" consistent. It would be ideal if they are in a split view with a grabbable divider, but I assume that would not be a trivial job refactoring the nibs.

**Comment by kainjow** [comment]
I don't think the split view would help because the hex views snap to fix based on the bytes per column, so you can't freely resize that without having wasted space.

**Comment by kainjow** [comment]
In 2c54cf96827c25ff321830e72f09e306a772fe4b you can hold down the Command key while resizing the window to resize the templates area.

**Comment by kumowoon1025** [comment]
> I don't think the split view would help because the hex views snap to fix based on the bytes per column, so you can't freely resize that without having wasted space.

Just a further enhancement request/qualification/question - the split could snap too?

Actually I'm thinking it'd be more flexible and look nicer as a separate window, maybe like the always-on-top hide-when-not-active-app style) in Preview (⌘I) or the selected item inspector in Finder (⌥⌘I)? Though not sure if anyone other than myself like the design idiom or if Big Sur human interface docs say anything about it.
