### ISSUE TITLE
Should Hex Fiend use the system alternating color?

### ISSUE THREAD

**Issue by kainjow** [ridiculousfish/HexFiend#266]
Hex Fiend has always used a custom blue color for the alternating row color:

<img width="531" alt="Screen Shot 2020-06-13 at 3 49 15 PM" src="https://user-images.githubusercontent.com/271035/84580669-c7111180-ad8d-11ea-8a19-a239586166bc.png">

But when dark mode was added, the [system color](https://developer.apple.com/documentation/appkit/nscolor/2998825-alternatingcontentbackgroundcolo?language=objc) was used instead.

Should Hex Fiend use this for light mode as well? Here's what it'd look like:

<img width="531" alt="Screen Shot 2020-06-13 at 3 47 32 PM" src="https://user-images.githubusercontent.com/271035/84580682-e90a9400-ad8d-11ea-9beb-140bf50c9bd0.png">

**Comment by kumowoon1025** [comment]
Huh, that's unexpected. There's probably a different system color that might bring out the contrast better, or maybe the one you can set in System Preferences.app

![accentcolor](https://user-images.githubusercontent.com/5461515/85644992-7be8df80-b666-11ea-91c0-f8b5d6dafc78.png)

I'll look up what it's called.

**Comment by kainjow** [comment]
[controlAccentColor](https://developer.apple.com/documentation/appkit/nscolor/3000782-controlaccentcolor?language=objc)?

In Big Sur the accent color can be any color now too.

The one issue I have is with custom highlighting and template colors. I think those should have more emphasis than the alternating row color, which is more just for alignment.

I'm thinking for the next major version default to the system color, but provide an option to use the "Hex Fiend Blue". I see that in Finder the accent color is not used for the alternating row color, so maybe that shouldn't be used there.

**Comment by gingerbeardman** [comment]
Seems fair.

I'm a system colour user myself.
