### ISSUE TITLE
Expose HFHexStringFromData & HFDataFromHexString

### ISSUE THREAD

**Issue by andrews05** [ridiculousfish/HexFiend#271]
The functions `HFHexStringFromData` & `HFDataFromHexString` are currently private, but I think they're highly useful functions and would love to have them available in the framework.

[edit] What I'm really wanting to do is get the selected characters from the view (either the hex or the ascii, depending on which has focus). There doesn't appear to be any easy way to do this currently.

**Comment by kainjow** [comment]
> What I'm really wanting to do is get the selected characters from the view

Which view?

**Comment by andrews05** [comment]
The HFTextView. There are functions to get the selected bytes, but I want to get the actual hex or ascii characters that the user has selected. I.e. the same characters you would get if you hit copy.

**Comment by kainjow** [comment]
yeah that function should work for hex. For ascii you can just use NSString initWithBytes directly.
