### ISSUE TITLE
"Text Encoding" menu becomes truncated if more than one custom encoding file is present

### ISSUE THREAD

**Issue by IvanExpert** [ridiculousfish/HexFiend#275]
If more than one custom encoding file is present, HexFiend will not show any custom encodings, nor the "Other..." option, in the Text Encoding menu.

That's really it. Steps to reproduce are to:
- quit HexFiend if running
- put two text encoding files in ~/Library/Application Support/com.ridiculousfish.HexFiend/Encodings
- open HexFiend
- click on Text Encoding menu
- observe that no custom text encodings, nor the "Other..." menu item, are present.

As an aside, I love this feature. It has allowed me to use HexFiend as a disk editor for Apple II disk image files, which often store their ASCII with high bit set. (I'm sure this is an extremely common and important use case.) Is the feature documented anywhere outside of https://github.com/ridiculousfish/HexFiend/issues/95#issuecomment-397858715 ? I was happy to have stumbled across it.

**Comment by kainjow** [comment]
Thanks to @ksherlock for the fix.
