### ISSUE TITLE
Framework: Reference cycle with HFTextView delegate

### ISSUE THREAD

**Issue by andrews05** [ridiculousfish/HexFiend#279]
I have an NSWindowController with an IBOutlet for an HFTextView. The window controller is also set as the text view's delegate so I can receive the properties changed callback.
My problem is the controller isn't released when closing the window and I've worked out that the cycle is caused by the delegate link. Is this an issue with the framework or am I doing something wrong?

Obviously I can just register for notifications instead of using the delegate, but using the delegate is simpler.
I'm working in Swift, if that matters. Framework v2.13.1.

**Comment by kainjow** [comment]
I think this should be fixed now. If you're able to test with master that'd be helpful.

**Comment by andrews05** [comment]
Yup, works now! Thanks heaps.
