### ISSUE TITLE
I am trying to achieve multi-colour text in a text representer but I still could not achieve good results. Any help ? Thanks

### ISSUE THREAD

**Issue by alfonsotesauro** [ridiculousfish/HexFiend#280]
I am trying to achieve multi-colour text in a text representer but I still could not achieve good results. Any help ? Thanks, you can read about the details here:

https://stackoverflow.com/questions/63432527/i-want-to-achieve-color-in-a-textview-driven-by-the-hexfiend-framework-i-almost

Many thanks for any help.

Alfonso

**Comment by alfonsotesauro** [comment]
Following another approach, I was able to draw the characters with a coloured background using the following code:

[[self.inMemoryController colorRanges] addObjectsFromArray:colorRangesArray];
[self.inMemoryController colorRangesDidChange];

This is not the solution I was looking for (see original question) but it is a nice to have. The only problem is that with many ranges, the HexFiend view resizing drastically decreases its resizing speed. If possible I would like a solution for this problem too. Thanks

**Comment by kainjow** [comment]
Unfortunately this isn't really well supported right now, especially since the main app doesn't use it for any main features.

In #181 I did some experiment work around this but haven't progressed. If more is done here it'll probably be related to that feature.
