### ISSUE TITLE
Add support for established binary description languages

### ISSUE THREAD

**Issue by aurelienmazurie-wk** [ridiculousfish/HexFiend#281]
The ability for **HexFiend** to parse a binary blob and produce a description of its content is quite helpful. It currently relies on a custom made, TCL-based DSL. Other DSLs exist, such as [Kaitai Struct](https://kaitai.io/) with which [multiple binary formats](https://formats.kaitai.io/) have been described. Having a way to accept Kaitai description files or possibly a way to translate these files into the HexFiend's DSL means we would suddenly be able to tap into that library.

**Comment by gingerbeardman** [comment]
But where to draw the line? Support them all?

I also posted about the formats supported by _010 Editor_ and _Synalyze It! Pro_ a long time ago https://github.com/ridiculousfish/HexFiend/issues/165#issuecomment-450493192

**Comment by ajmazurie** [comment]
The line should be drawn at whatever brings the highest number of existing binary format descriptions for the minimum amount of work.

**Comment by kainjow** [comment]
Previous threads on this topic:
https://github.com/ridiculousfish/HexFiend/issues/189
https://github.com/ridiculousfish/HexFiend/issues/89#issuecomment-354699618

**Comment by kainjow** [comment]
I took a deeper look at this the other day.

I does appear that Kaitai has a compile written in Scala that can be compiled to [JavaScript](https://github.com/kaitai-io/kaitai_struct_compiler/tree/master/js). Theoretically, you could take a pre-built version of that, and all its dependencies, assuming they can be ported or migrated out of Node, and make them run under [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore). However, I tried to find the code that creates the "object tree" used in the web IDE, and it appears to be some gnarly code that walks the JavaScript generated object tree, based on their types. My understanding is Kaitai generates code specific to the format, to be able to parse the file in a specific way, whereas Hex Fiend doesn't care about that programmatically. It just wants that object tree.

Another problem with their JS code is it [doesn't support BigInt](https://github.com/kaitai-io/kaitai_struct/issues/183), which is required to properly support 64-bit unsigned integers.
