### ISSUE TITLE
Columns header moves two columns right after open or create a new window

### ISSUE THREAD

**Issue by LiJinyao** [ridiculousfish/HexFiend#282]
When I enable View->columns, HexFiend shows columns header in right position when it launch. But after create a new window of open a file, the new created window's columns header shifts two columns to the right.
![image](https://user-images.githubusercontent.com/3450595/93636740-07d09480-fa27-11ea-83ba-7d75ed27d883.png)

My system is macOS 10.15.6 (19G2021)
HexFiend Version 2.13.1 (1593833290)

**Comment by gingerbeardman** [comment]
FWIW, I cannot reproduce this on 10.14.6 (18G4032)
