### ISSUE TITLE
SMJobBless fails on 10.9

### ISSUE THREAD

**Issue by krackers** [ridiculousfish/HexFiend#286]
As I added in a comment in #214, on 10.9 SMJobBless seems to fail with the following:
```
10/21/20 4:18:50.452 PM launchdadd[23465]: FAILURE: Code <SecStaticCode 0x7fc198f0d7e0 [0x7fff7b209f00]> failed requirement (identifier "com.ridiculousfish.HexFiend.PrivilegedHelper" and certificate leaf[subject.CN] = "Developer ID Application: Kevin Wojniak") with error "The operation couldn’t be completed. (OSStatus error -67050.)"
```

```
10/21/20 4:18:50.452 PM launchdadd[23465]: FAILURE: Job com.ridiculousfish.HexFiend.PrivilegedHelper could not be installed from /Applications/Hex Fiend.app/Contents/Library/LaunchServices/com.ridiculousfish.HexFiend.PrivilegedHelper, reason 3.
```

This behavior only seemed to start from Hex Fiend 2.9 onwards (it works fine in 2.8). The setup of `SMPrivilegedExecutables` key-value in the `info.plist` of the main app and embedded in the executable of the helper tool seems identical between the working and broken version, so I'm really not sure what could be the cause. 

Since you've previously mentioned that the privilege-escalation part is hacky and not something you're committed to, feel free to close this as a wontfix if needed – I just wanted to document the issue for the future.

**Comment by kainjow** [comment]
Thanks for the details. It's probably related to #257. I'm going to close this out for that thread.
