### ISSUE TITLE
Feature Request: Show the number of results in search. 

### ISSUE THREAD

**Issue by hffaust** [ridiculousfish/HexFiend#288]
I was using Hex Fiend to search through a binary and I was searching for a specific series of hex bytes. The search worked perfectly but, there were several occurrences of the series. I know that I could use the  `Next` button to iterate through each occurrence and then count how many times I iterate until I reach my initial start point. In a small file with few occurrences this is not an issue at all. *However, in a large file, such as the one I was analyzing, this is quite tedious.* 

**It would be great if the number of matching search results could be displayed so that the user could see the number of occurrences without any extra hassle.** I imagine that the program already knows the number of found items behind the scenes so outputting this to the user interface should be trivial.

**Comment by hffaust** [comment]
I saw in the closed issue history that someone else already requested this and it was denied. I still think it would be a great feature if the devs would reconsider adding it.

**Comment by gingerbeardman** [comment]
Agreed, the previous issue was #236

**Comment by kumowoon1025** [comment]
Don't quote me on this but I think the search takes at least linear time, depending on some function of the length of the pattern and the whole file, for short patterns. I think the rationale is avoiding the possibility of being stuck after doing a "Find all" unless searches can be cancelled? I think it was mentioned a while ago, not sure if it was here. 

Plus there are some kinks in finding number of occurrences in general, like if you search for `0xAB 0xAB` in `0xABABABABABABABAB` are there 7 occurrences or 4?

**Comment by jb4690world** [comment]
+1 agree, this would be a great feature (Count).  Personally I don't think the time it would take to find all occurrences to be an "issue".  My use case is simple, count the number of times a specified byte pattern matched in the file.
