### ISSUE TITLE
What's the latest official/stable version?

### ISSUE THREAD

**Issue by shurcooL** [ridiculousfish/HexFiend#47]
If one looks at https://github.com/ridiculousfish/HexFiend/releases, it seems the latest version is 2.3.0.

However, on the [main website](http://ridiculousfish.com/hexfiend/), it lists 2.1.2 as the latest version (it's what you get if you press Download, and also [Release History](http://ridiculousfish.com/hexfiend/ReleaseNotes.html) only goes up to 2.1.2).

Is the latest official/stable version 2.3.0 or 2.1.2?

**Comment by kainjow** [comment]
v2.4 was just released. Should be stable.
