### ISSUE TITLE
Can't save a document with ".dat" as an extension

### ISSUE THREAD

**Issue by percontation** [ridiculousfish/HexFiend#50]
Opening a new document and attempting to name it "foo.dat" reveals some kind of bug.

> You cannot save this document with extension “.dat” at the end of the name. The required extension is “.(null)”.

This appears to be specific to ".dat" as an extension. Huh.

**Comment by kainjow** [comment]
Works for me with a build from Xcode 8.1 on 10.12.1.

**Comment by percontation** [comment]
@kainjow: What about if you try saving with a name like `test.bundle`? The problem is with extensions that are bound to a UTI that does not inherit from one listed in the CFBundleDocumentTypes. I still see this issue on 10.11.

**Comment by kainjow** [comment]
I get that dialog if I choose "Data". If I select "All Types" .dat and .bundle work.

**Comment by percontation** [comment]
Ah, yeah. I guess we should find a way to kill that section of the dialog (and always do whatever All Types is doing).

**Comment by kainjow** [comment]
Apparently NSSavePanel has allowsOtherFileTypes. in BaseDataDocument's prepareSavePanel: I set that to YES, and it allowed saving as .jpg when Data was selected.

So then do we need the Other and Data document types in Info.plist?

**Comment by percontation** [comment]
Yes, to support Open With > Hex Fiend from the Finder context menu.

**Comment by kainjow** [comment]
allowsOtherFileTypes still requires using allowedFileTypes to set which other file types are allowed, so even with that set it still warns about .bundle when Data is selected, but if I set allowedFileTypes to kUTTypeBundle then it works. So technically if we got all known UTIs we could manually list them, but that seems clunky.

**Comment by percontation** [comment]
Hmm, does adding

```
    savePanel.allowedFileTypes = nil;
    savePanel.allowsOtherFileTypes = YES;
```

to that prepareSavePanel method at least partially fix this for you? I can still manage pop the "(null)" dialog though some combination of first saving as "Other" and then trying to Save As "Data"... but at least the case of wanting to save a new document with a weird extension seems to work with those properties set.

**Comment by kainjow** [comment]
Actually I'm not sure allowsOtherFileTypes actually made any difference, now that I'm trying to test again without it and can still save with .jpg. I cannot either way save with .bundle unless I use AllTypes.

Since this is an OS X bug and using AllTypes solves the problem, maybe we shouldn't worry too much about workarounds?

The use of CFBundleTypeOSTypes is deprecated as of 10.5 anyways, so it's bound to stop working at some point.

**Comment by kainjow** [comment]
8c44e6efe9de364c1fce7ebe7b9c83063ce05564 removed the file type option altogether. Saving with .dat or .bundle works. I'm closing this again.
