### ISSUE TITLE
Cannot Browse Inside .APP Directory

### ISSUE THREAD

**Issue by jaredjones** [ridiculousfish/HexFiend#51]
Version: 2.1.2 (200)
Whenever I go to File->Open and select a .app file, the program treats this as a file and not as a directory. So if for instance I want to view the MacOS binary of an app file, I have to manually drag it to my Desktop first and then place it into hex fiend.
Hex Fiend should be able to see inside a .app directory.

**Comment by kainjow** [comment]
Added in 7f3ba634f93100eeeed37e0ddaa18790e7bdc49a
