### ISSUE TITLE
Permissions for Sparkle.framework not correctly set

### ISSUE THREAD

**Issue by szhu** [ridiculousfish/HexFiend#52]
_See also caskroom/homebrew-cask#9895._

Hex Fiend does not correctly set 'group' and 'other' permissions and will crash if a non-owner runs it. The buggy files are fixed by updating their 'group' and 'other' permissions to reflect the 'user' permissions: `chmod go=u`.

---

![screen shot 2015-03-05 at 3 25 38 am](https://cloud.githubusercontent.com/assets/1570168/6504013/540e4036-c2e7-11e4-885f-9f76a4991b43.png)

```
$ '/opt/homebrew-cask/Caskroom/hex-fiend/2.3.0/Hex Fiend.app/Contents/MacOS/Hex Fiend'
dyld: Library not loaded: @loader_path/../Frameworks/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /opt/homebrew-cask/Caskroom/hex-fiend/2.3.0/Hex Fiend.app/Contents/MacOS/Hex Fiend
  Reason: no suitable image found.  Did find:
    /opt/homebrew-cask/Caskroom/hex-fiend/2.3.0/Hex Fiend.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: stat() failed with errno=13
    /opt/homebrew-cask/Caskroom/hex-fiend/2.3.0/Hex Fiend.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: stat() failed with errno=13
```

```
$ ll '/opt/homebrew-cask/Caskroom/hex-fiend/2.3.0/Hex Fiend.app/Contents/Frameworks/'
total 0
drwxr-xr-x  6 Administrator   204B Mar  5 03:16 HexFiend.framework/
drwx------  6 Administrator   204B Mar  5 03:16 Sparkle.framework/
```

**Comment by percontation** [comment]
This doesn't reproduce for me under `xcodebuild`, so I'm not sure how to find a fix. I just updated Sparkle in f359ade105 and hit the Xcode project file a few times, so hopefully that helps?

(Tangentially, `chmod go=u` seems ill advised, as that in most cases that would grant unprivileged users the ability to modify the Sparkle binaries.)

**Comment by zorgiepoo** [comment]
My bet is something went wrong when archiving the app.

**Comment by kainjow** [comment]
I think newer Xcode versions are using saner defaults for this, since when looking at the current 2.3 version I see the invalid permissions for Sparkle, but when I look at a fresh new Xcode 8.1 build the permissions are 755. Either way this appears to be fixed for the upcoming version.
