### ISSUE TITLE
Hide 00 bytes

### ISSUE THREAD

**Issue by adius** [ridiculousfish/HexFiend#53]
It would be really cool if there was a menu to hide all the 00 bytes.
Any chance this will get implemented? =)

**Comment by percontation** [comment]
Sounds reasonable, I'd merge such a pull request.

If you'd like something comparable immediately, you can turn on byte coloring with "Font > Color bytes" and tweak the byte-coloring code on HFTextRepresenter.m:264 to, for example, return black when `byte == 0` and transparent for all other bytes.

**Comment by Frizlab** [comment]
Done in #56 :)

**Comment by percontation** [comment]
Thanks!

**Comment by JanX2** [comment]
@adius Interesting! What application does this have?

**Comment by adius** [comment]
Just to able to see at a glance which bytes are not 00.
Comes in handy for file-types which may have a lot of 00s.
