### ISSUE TITLE
Is it published to AppStore?

### ISSUE THREAD

**Issue by bolasblack** [ridiculousfish/HexFiend#55]
I found [an app in appstore](https://itunes.apple.com/us/app/ihex-hex-editor/id909566003?mt=12) really like HexFiend, is it you published by you?

**Comment by percontation** [comment]
No, it isn't. There are several derivative AppStore copies of HexFiend, which is a bit unfortunate (but totally allowed provided that they meet the the BSD license conditions).

There isn't an "official" version of HexFiend on the AppStore for various reasons.
