### ISSUE TITLE
Line breaks?

### ISSUE THREAD

**Issue by aramk** [ridiculousfish/HexFiend#57]
I use HexFiend to open very large files in text mode and was wondering if there's any support for line breaks? Currently it's all condensed for HEX editing only. Thanks!

**Comment by kainjow** [comment]
This really doesn't belong in a hex editor, in my opinion. Most GUI programs choke on large files, although BBEdit is pretty good. You could also use Terminal and use the command `cat /path/to/file | more`

**Comment by ridiculousfish** [comment]
Hi Aram,

Nope, it's just a hex editor. If it did line breaks then it would be a text editor :)

_fish

**Comment by aramk** [comment]
Thanks for the replies guys. Could you recommend a text editor that supports large files on the Mac? Is it due to the line breaks that GUI programs choke? Looks like `less` is preferred for large files and you can skip forwards and backwards, so that works great for my needs for now. Cheers!

**Comment by annttiigs** [comment]
Hi fish & guys,

We are still free to implement line breaks into it right ? Clone and modify :)

_LgN

**Comment by kainjow** [comment]
Yep must make sure you follow the license.

**Comment by annttiigs** [comment]
For sure,

I will keep an eye on it, and this will be for my personal usage only (If I can make it). I have been looking for something like notepad++ on mac (fast and light) and finally found it. 

_LgN

**Comment by chstdu** [comment]
Did you succeed in implementing line breaks? I would need a small tool like HexFiend to open huge files to quickly scan the correct line formatting without always having to remember how to toggle line numbers in the common command line tools.

**Comment by mhuebner** [comment]
Would also love to have linebreaks!

**Comment by themacmarketer** [comment]
Adding one more vote for this.

**Comment by franciskim** [comment]
Voting for linebreaks

**Comment by gingerbeardman** [comment]
Just use BBEdit.

**Comment by franciskim** [comment]
> Just use BBEdit.

Unfortunately the performance is quite different. I wonder if implementing line breaks is what reduces performance?

**Comment by gingerbeardman** [comment]
How big are your text files?

Other recommendations: 
- https://apple.stackexchange.com/questions/3437/whats-the-best-text-editor-for-use-with-large-files
- https://stackoverflow.com/questions/952886/editing-large-files-on-mac-os-x

Would be interested your findings!

**Comment by RealRTTV** [comment]
Hey, um is there any good super large text editors or even viewers for huge files with a find and search system, that's really all I need for reading my massive logs

**Comment by onasipim** [comment]
The best for me so far for macOS is: https://github.com/nickbnf/glogg

**Comment by olgunkaya** [comment]
I unfortunately could not focus on this to implement LBs after the initial checks.
