### ISSUE TITLE
Claim copyrights on MacAppStore to re-branded iHex fork

### ISSUE THREAD

**Issue by nanoant** [ridiculousfish/HexFiend#59]
Sorry to raise that, but it is really a pity to see [iHex app on MacAppStore](https://itunes.apple.com/us/app/ihex-hex-editor/id909566003?mt=12) which is obvious shameless fork of HexFiend that doesn't keep the attribution and copyrights in its binaries as required by the 2-clause BSD license, eg: `© hewbo.com` on the page and inside the app itself, see below.

So it would be cool if the original author could contact Apple at https://www.apple.com/legal/internet-services/itunes/appstorenotices/#/contacts and ask them to tear down this app from Mac App Store.

![iHex about box](https://cloud.githubusercontent.com/assets/103067/10689364/f652022a-797a-11e5-802a-c2702bc1e70a.png) ![iHex app](https://cloud.githubusercontent.com/assets/103067/10689361/f2ae55f6-797a-11e5-8181-d897322654ab.png)

**Comment by ricwein** [comment]
+1 ... it's sadly still available on the Mac Appstore

**Comment by bumblebritches57** [comment]
I actually use this app from time to time, and from what I can tell they load iHex as an external framework, and the interface is similar, but they do provide more options.

Wether that nullifies the copyright claim or not, I have no clue.

**Comment by qayshp** [comment]
The app in the AppStore is just the latest code built and with rebranding. As far as I can tell, the only different features between the "official" download of HexFiend and iHex are already checked into the code here. Byte coloring and the additional data inspector types work if you clone this repo and build the app yourself.

This is a violation of the 2 clause BSD license as there is no credit given to the original.

https://github.com/ridiculousfish/HexFiend/blob/master/License.txt
"Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution."

**Comment by bumblebritches57** [comment]
@ridiculousfish I tried contacting Apple on your behalf, but that's not how it works.

You can file an IP claim against the developer of iHex, Li Jianyu aka hewbo.com here: http://www.apple.com/legal/internet-services/itunes/appstorenotices/#/contacts?lang=en

**Comment by kainjow** [comment]
Closing, nothing can be done here by anyone except for @ridiculousfish - anyone else wishing to contact him may use the email listed at http://ridiculousfish.com/hexfiend/

**Comment by gingerbeardman** [comment]
I just filed a bug report/suggestion with Apple about this, https://bugreport.apple.com

When I worked there I had clones like this taken down. So I'm hopeful.

There are now 5 clones.

https://itunes.apple.com/gb/app/ihex-hex-editor/id909566003?mt=12
https://itunes.apple.com/gb/app/hex-editor/id729464049?mt=12
https://itunes.apple.com/gb/app/hex-edit-pro/id803736440?mt=12
https://itunes.apple.com/gb/app/hex/id670555299?mt=12
https://itunes.apple.com/gb/app/hexeditor-pro/id755076884?mt=12
