### ISSUE TITLE
UTF-8 doesn't get read correctly.

### ISSUE THREAD

**Issue by KendallHopkins** [ridiculousfish/HexFiend#6]
HexFiend doesn't seem to read UTF-8 correctly (I changed the encoding in the menu and I'm running 2.1.1). I've attached two images below: one in HexFiend and one in SubEthaEdit. SubEthaEdit reads it correctly while Hex Fiend doesn't. Hex Fiend rendering of the text looks very similar to how it reads the file when set to Latin1.

![hexfiend](http://i.imgur.com/XGlHj.png)

![subetha](http://i.imgur.com/9hXof.png)

**Comment by kainjow** [comment]
Tracking this in #185
