### ISSUE TITLE
Support Drag file to  HexFiend

### ISSUE THREAD

**Issue by fancymax** [ridiculousfish/HexFiend#61]
Drag a file to HexFiend,then it can open the file.
It's inconvenient to use Open File or Open Path Command.

**Comment by ridiculousfish** [comment]
Are you dragging it into a Hex Fiend window? You can drag it onto the icon (in the Dock, or in Finder).

**Comment by bumblebritches57** [comment]
Yes, dragging into the window would be nice.

it's literally the only reason I use iHex over Hex Fiend.

**Comment by ridiculousfish** [comment]
Ok, seems reasonable.

**Comment by kainjow** [comment]
This already works for me on 2.3.0. I can drag files onto the app icon in the Dock, and HF windows.

If it's not working, please provide more specifics, such as the exact type of file you're using.
