### ISSUE TITLE
UTF8 words are not shown correctly

### ISSUE THREAD

**Issue by vhdmsm** [ridiculousfish/HexFiend#63]
It would be really nice to fix showing of utf8 words. I've attached a picture of this issue:
![screen shot 1395-01-16 at 13 43 16](https://cloud.githubusercontent.com/assets/6222662/14243527/4a5fcf48-fa6b-11e5-9278-6c13b878a030.png)
![screen shot 1395-01-16 at 13 43 33](https://cloud.githubusercontent.com/assets/6222662/14243525/4a4e7a86-fa6b-11e5-98ba-28fbf201753a.png)

**Comment by kainjow** [comment]
The problem is mapping bytes to characters, which doesn't work for multi-byte characters. The UTF8 inspector solves this.

**Comment by bumblebritches57** [comment]
Yup, UTF-8 is a PITA  when it comes to use visible "characters". look up "Graphemes" for more info.

**Comment by kainjow** [comment]
Tracking this in #185
