### ISSUE TITLE
Add view option to display hex column header at top row and first column

### ISSUE THREAD

**Issue by esutton** [ridiculousfish/HexFiend#64]
I _really_ wish it had an option to display a hex column header on the top row and first column.

Like this

```
00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
10 
20
30
.
.
d0
e0
f0
```

And maybe a decimal option for the header too!

Thank you for a good app!

**Comment by percontation** [comment]
When you say "first column", do you mean something different than the column that appears when "Views > Line Numbers" is enabled?

**Comment by esutton** [comment]
Same thing but I prefer line numbers to display in hexadecimal.

The first row header should display 16 column headings from 00 to FF.

Something like this screenshot shown below:

![screen shot 2016-08-01 at 8 29 42 am](https://cloud.githubusercontent.com/assets/6115047/17295544/35c54bbc-57c2-11e6-9d14-f8ef187b6c7a.png)

**Comment by percontation** [comment]
Hexadecimal line numbers are implemented, but a bit hidden. If you click on the line numbers, they toggle between decimal and hexadecimal :)

Displaying an optional floating header row when the window is sized to a multiple of 16 bytes sounds like a nice feature.

**Comment by esutton** [comment]
That was not obvious.  Thanks for the tip! 

Could some sub-menus be added?

```
View
  [ x ] Line Numbers
          [ x ] Hexadecimal
           [   ] Decimal
```

And the Hex or Dec checkmark state would be remembered even when Line Numbers is unchecked.

**Comment by gingerbeardman** [comment]
Would also appreciate this.

**Comment by kainjow** [comment]
Experimented with this a little. Turned off the gradient in the line counts for this to look better together:

<img width="579" alt="untitled" src="https://user-images.githubusercontent.com/271035/50583294-2212ab00-0e1d-11e9-8937-2641c9980bb1.png">

**Comment by esutton** [comment]
@kainjow Thank you!  

I replaced the release build with a build made from the columns branch.

**Comment by kainjow** [comment]
Finished this up and merged the columns branch into master.
