### ISSUE TITLE
Feature request - copy/paste to/from base64

### ISSUE THREAD

**Issue by colde** [ridiculousfish/HexFiend#65]
I often have to handle binary data encoded as base64 and it would be a great feature to be able to use that directly in hex fiend by pasting it directly into an empty document, and being able to then copy it back to base64 after making changes.

Also, thanks for an awesome little editor!

**Comment by bumblebritches57** [comment]
You can just open Terminal, copy the code, and run `base64 -D -i - -o ~/Desktop/Output.bin`

**Comment by colde** [comment]
@bumblebritches57 Yeah, i am not saying it is hard, it would just be a handy feature.

**Comment by kainjow** [comment]
Pull requests are always welcomed.
