### ISSUE TITLE
Protobuf support question

### ISSUE THREAD

**Issue by jesusgalvan** [ridiculousfish/HexFiend#68]
I am trying to view a protobuf encoded file, a [Dota2](https://github.com/skadistats/smoke/wiki/Anatomy-of-a-Dota-2-Replay-File) replay file to be exact (.dem).

Is it possible that one of the existing encodings already supports this encoding?

**Comment by percontation** [comment]
Hex Fiend doesn't have any special support for particular file formats. (It's probably the wrong tool for the job if you're looking to view protobuf-serialized data.)
