### ISSUE TITLE
App hangs when pasting

### ISSUE THREAD

**Issue by ElfSundae** [ridiculousfish/HexFiend#69]
Copy something within HexFiend, then paste it to any other app, that app will hang (Not Responding), even the Clipboard Viewer.  I can not copy anything out from HexFiend now. How to fix this?

```
Date/Time:       2016-11-13 21:19:29 +0800
OS Version:      Mac OS X 10.11.6 (Build 15G1108)
Architecture:    x86_64
Report Version:  22

Command:         Hex Fiend
Path:            /Applications/Hex Fiend.app/Contents/MacOS/Hex Fiend
Version:         2.3.0 (300)
Parent:          launchd [1]
PID:             18984

Event:           hang
Duration:        1.10s (process was unresponsive for 19 seconds before sampling)
Steps:           11 (100ms sampling interval)

Hardware model:  MacBookPro9,2
Active cpus:     4

Fan speed:       2000 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  11  start + 52 (Hex Fiend + 5764) [0x1033c7684]
  11  NSApplicationMain + 1176 (AppKit + 25448) [0x7fff8dcbc368]
  11  -[NSApplication run] + 682 (AppKit + 249216) [0x7fff8dcf2d80]
  11  -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454 (AppKit + 295462) [0x7fff8dcfe226]
  11  _DPSNextEvent + 1067 (AppKit + 298486) [0x7fff8dcfedf6]
  11  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 198063) [0x7fff91c895af]
  11  ReceiveNextEventCommon + 432 (HIToolbox + 198511) [0x7fff91c8976f]
  11  RunCurrentEventLoopInMode + 235 (HIToolbox + 198965) [0x7fff91c89935]
  11  CFRunLoopRunSpecific + 296 (CoreFoundation + 560696) [0x7fff9c953e38]
  11  __CFRunLoopRun + 2171 (CoreFoundation + 563483) [0x7fff9c95491b]
  11  __CFRunLoopDoSource1 + 473 (CoreFoundation + 597737) [0x7fff9c95cee9]
  11  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41 (CoreFoundation + 597881) [0x7fff9c95cf79]
  11  __CFMessagePortPerform + 584 (CoreFoundation + 1222024) [0x7fff9c9f5588]
  11  __CFPasteboardClientCallBack + 1364 (CoreFoundation + 1370980) [0x7fff9ca19b64]
  11  __NSPasteboardProvideData + 331 (AppKit + 3789799) [0x7fff8e0533e7]
  11  ??? (<F2902C2B-A30D-3D57-8738-C1E56A8C3B97> + 145645) [0x1034788ed]
  11  ??? (<F2902C2B-A30D-3D57-8738-C1E56A8C3B97> + 144405) [0x103478415]
  11  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270 (Foundation + 151257) [0x7fff9f91bed9]
  11  CFRunLoopRunSpecific + 296 (CoreFoundation + 560696) [0x7fff9c953e38]
  11  __CFRunLoopRun + 1356 (CoreFoundation + 562668) [0x7fff9c9545ec]
  11  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 565540) [0x7fff9c955124]
  11  mach_msg_trap + 10 (libsystem_kernel.dylib + 69490) [0x7fff92f20f72]
 *11  ipc_mqueue_receive_continue + 0 (kernel + 812688) [0xffffff80002c6690]


Process:         Hex Fiend [18984]
Path:            /Applications/Hex Fiend.app/Contents/MacOS/Hex Fiend
Architecture:    x86_64
Parent:          launchd [1]
UID:             501
Task size:       8069 pages
Note:            Unresponsive for 19 seconds before sampling

  Thread 0x16d26          DispatchQueue 1         11 samples (1-11)       priority 46 (base 46)
```
Full log: [log.txt](https://github.com/ridiculousfish/HexFiend/files/587770/log.txt)

**Comment by percontation** [comment]
Hmm, I'm not sure I quite understand the issue. The log makes it look like Hex Fiend is hanging, but you say other apps are hanging?

I also note several apps running that may be interacting with the clipboard ("Clipboard Viewer", "ClipMenu", maybe "Dash"?). It seems vaguely plausible that having one of those running may be what's triggering the bug for you. Does your issue reproduce without any such apps running?

**Comment by ElfSundae** [comment]
Thank you, for every time the target app will hang, and sometimes Hex Fiend will also hang.

**Comment by ElfSundae** [comment]
I just quitted Clipboard Viewer, ClipMenu and Dash, then opened Hex Fiend and typed some words, then copied some characters via cmd+c, and then cmd+v in a new TextEdit document, the TextEdit hanged. 

[TextEdit Report.txt](https://github.com/ridiculousfish/HexFiend/files/589512/TextEdit.Report.txt)

BTW, doing copy/paste via Edit menu item or via keyboard shortcut has no difference.

If I "Force Quit" TextEdit when it is hanging, Hex Fiend will hang then. 
[Hex Fiend Report.txt](https://github.com/ridiculousfish/HexFiend/files/589524/Hex.Fiend.Report.txt)

**Comment by ElfSundae** [comment]
I guess maybe it is an OS issue.

**Comment by percontation** [comment]
Thanks for the additional info. Even if it's an OS issue, there's probably some way to work around it, since I'm also still on 10.11.6, and so far copy-paste has worked. I'll keep my eyes open.

**Comment by percontation** [comment]
(If you or anyone has additional info that would help me repro copy-paste failures, do share, 'cause I'm probably not going to throw myself at this issue without being able to repro locally.)

**Comment by kainjow** [comment]
I can reproduce this on 10.12.1. I remember seeing it before too. Seems you do have to paste in another app, and then (not necessarily right away), HF will also hang in `[HFPasteboardOwner moveDataWithProgressReportingToPasteboard:forType:]`

**Comment by kainjow** [comment]
I can't reproduce when running out of Xcode now. I don't see any changes that may have affected it directly since the last release build (July 2014).

**Comment by ElfSundae** [comment]
Thanks. I have met this issue for a year since I upgraded (not clean install) OS from 10.10. Maybe it is an OS bug, but for me it is only occurred when I paste from HF to other apps.

**Comment by ElfSundae** [comment]
I just cloned & built from source, it works now! 🎉   Thank you again! 🚀
