### ISSUE TITLE
2.4 version and drop 10.7?

### ISSUE THREAD

**Issue by kainjow** [ridiculousfish/HexFiend#70]
It's been almost 2.5 years since the last release, I think it's time for a new one. I think we should drop 10.7, as there are several branches in the code that split off for 10.8+ functionality, so it will let us simplify things. Also bump to version 2.4.

@percontation

**Comment by percontation** [comment]
Sounds good. My call would be waiting to drop the 10.7 code until after the release.

**Comment by kainjow** [comment]
OK, I bumped the version - think it's ready for release if you want to make the build.

**Comment by percontation** [comment]
👍 I'll get around to it in a bit. I feel obliged throw 10.7 (or at least, like, 10.9) on a VM to make sure the release launches there first.

**Comment by kainjow** [comment]
I made a build via `xcodebuild -config Release -scheme "Release"` and tested on 10.7 without any issues.

**Comment by percontation** [comment]
Great, sounds like we're set then. Go ahead and post it!

**Comment by kainjow** [comment]
I don't have the certificate that was used for the last build, which is self-signed. We really should use a developer ID certificate to avoid warnings when opening. What do you think?

**Comment by percontation** [comment]
Right, IIRC I just made a temporary cert to sign the last release (I vaguely remember something not working right if there was no signing at all, maybe an issue surrounding the privileged helper tool?).

If you have an official cert and would be willing to sign HexFiend, that'd be sweet. If not, meh, not worth $99 to me :|

**Comment by kainjow** [comment]
Ok, I'll look into it tonight. Will need to update the project because the code signing identity needs to be put in the Info.plists. I'll try to make it generic.

**Comment by bumblebritches57** [comment]
In Xcode 8 you kinda have to sign it, but now your Apple ID includes a private certificate for free.

Since you're not distributing this on the App Store, I don't see why that wouldn't work.

**Comment by kainjow** [comment]
Just posted v2.4 release using my Developer ID.
