### ISSUE TITLE
Host webpage on GitHub pages?

### ISSUE THREAD

**Issue by kainjow** [ridiculousfish/HexFiend#71]
@ridiculousfish @percontation 

What do you think about hosting the existing website http://ridiculousfish.com/hexfiend/ on GitHub pages? Then we can update it directly.

**Comment by ridiculousfish** [comment]
Sure. The page is simple - what can I do to help?

**Comment by kainjow** [comment]
In Settings you can turn on GitHub Pages for the project:

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

There are options to use a `gh-pages` branch, or the `master` branch with `/docs` directory. I think using `/docs/` on `master` would be cleanest.

Either way once setup the URL should be http://ridiculousfish.github.io/hexfiend based on what I've read at https://help.github.com/articles/user-organization-and-project-pages/

**Comment by ridiculousfish** [comment]
Ok done! The reported URL is http://ridiculousfish.github.io/HexFiend/ 

I've put a zipped copy of the site at [http://ridiculousfish.com/hexfiend_site.zip](http://ridiculousfish.com/hexfiend_site.zip). ~4.8 MB.

**Comment by kainjow** [comment]
Thanks! It seems to be generally working.

**Comment by kainjow** [comment]
OK, after some cleanup I think the GH Pages site is good for now. I changed the HF1 link to go to your website. Do you want to update the HF project URL to use GH Pages? Maybe update your website's URL too so people don't get confused with two sites.

**Comment by bumblebritches57** [comment]
Where are the releases?

The GitHub page doesn't show up anymore, and the old page still links to HexFiend 2.3

**Comment by kainjow** [comment]
@bumblebritches57 the releases are on the main project page - click on releases next to contributors and the license. You'll end up at https://github.com/ridiculousfish/HexFiend/releases

**Comment by bumblebritches57** [comment]
Thanks! I feel like I've seen that button a thousand times, but I never remember where it is (or maybe Github just moves it around?)

**Comment by kainjow** [comment]
@ridiculousfish should the project URL be updated to http://ridiculousfish.github.io/HexFiend/ ?

**Comment by ridiculousfish** [comment]
I'd rather keep it where it is, but I updated my page http://ridiculousfish.com/hexfiend/ to point to the most recent release a while back, and I plan to keep it updated.
