### ISSUE TITLE
Menus are very slow

### ISSUE THREAD

**Issue by fzwo** [ridiculousfish/HexFiend#72]
Using Hex Fiend 2.4, clicking a menu takes more than a second for anything to happen on a 2016 rMBP. Doesn't matter if I have a file open or not.

**Comment by fzwo** [comment]
Sometimes, or after a while (I haven't yet found out), menus are back to normal speed.

This is on a relatively fresh install of Sierra, with a freshly downloaded Hex Fiend.

**Comment by bumblebritches57** [comment]
It's plenty fast on my 2012 retina.

Maybe it's related to the new LCD function key thing?

**Comment by fzwo** [comment]
It's fast today (even though I didn't reboot or anything). Strange. Menus in other apps were also fast when I noticed the issue in Hex Fiend, but some other things, like opening the New Tweet window in Tweetbot, were also slow (and are fast now).

Was probably something wrong with my system. Sorry for the noise.
