### ISSUE TITLE
Are you the iHex on MacAppStore?

### ISSUE THREAD

**Issue by Oyangiz** [ridiculousfish/HexFiend#76]
Are you the iHex on MacAppStore?
I found it and it looks like HexFiend, but I can not found the license and this project name.
Is it a copier？
<img width="396" alt="jietu20170304-145708" src="https://cloud.githubusercontent.com/assets/11882176/23576873/a0a5af80-00eb-11e7-8d90-95aea2047e92.png">

**Comment by nlsn** [comment]
I'm also curious if iHex is copied from Hex Fiend. They appear to be the same.

**Comment by ridiculousfish** [comment]
Yeah, there's at least one repackaged Hex Fiend :(

**Comment by nlsn** [comment]
Makes me wonder what nefarious crap may have been added in the repackaging process.

**Comment by tholu** [comment]
Duplicate of https://github.com/ridiculousfish/HexFiend/issues/59.
