### ISSUE TITLE
Feature request - open file in HexFiend from Terminal

### ISSUE THREAD

**Issue by tholu** [ridiculousfish/HexFiend#77]
Similar to the `subl` command for Sublime Text, it would be great to have a short command to open a file in HexFiend from the terminal, e.g. `hexf`.

Or is this already possible?

**Comment by tholu** [comment]
I'm currently using this workaround in my `.zshrc`, which also works well:

```zsh
# hex fiend
hexf() {
  open -a "Hex Fiend" $1
}
```

**Comment by kainjow** [comment]
It could be done, using a shell script similar to what you've got. Where should it be stored? /usr/local/bin/hexf ?

**Comment by tholu** [comment]
`/usr/local/bin/` sounds like the right location, yes.

**Comment by kainjow** [comment]
I published a beta here if you'd like to test it out:

https://github.com/ridiculousfish/HexFiend/releases/tag/v2.6.0b1
