### ISSUE TITLE
Command Line Tools Installation Fails on OS X 10.12.3

### ISSUE THREAD

**Issue by jkroes** [ridiculousfish/HexFiend#79]
Possibly because of the new System Integrity Protection in place since OS X El Capitan, the command line tools can't be installed to /bin. I haven't tried to install without SIP, so I can't comment on whether or not that works. Installing to /usr/local/bin would be one workaround.

**Comment by kainjow** [comment]
What's the error you get?

**Comment by jkroes** [comment]
Error message: "'hexf' couldn’t be copied because you don’t have permission to access “\'bin'. To view or change permissions, select the item in the Finder and choose File > Get Info."

Even with SIP disabled and modifying Finder permissions to allow Everyone to read and write to /bin, the error message continued.

**Comment by kainjow** [comment]
Does `/usr/local/bin` already exist?

**Comment by jkroes** [comment]
It does on my system because some packages have installed binaries there, but I don't think it does in a fresh system install.

**Comment by kainjow** [comment]
I think it's just referring to the last path component "bin".

Can you run this command, and post the output?

    ls -ald /usr/local/bin

For me it looks like this:

    drwxr-xr-x  298 kainjow  admin  10132 Mar  1 14:28 /usr/local/bin

**Comment by jkroes** [comment]
drwxr-xr-x  59 root  wheel  2006 Mar 30 23:55 /usr/local/bin

**Comment by kainjow** [comment]
Well that explains it, it's owned by root. You could try `sudo chown $USER /usr/local/bin`

**Comment by jkroes** [comment]
Fixed.
