### ISSUE TITLE
allow users to add text to bookmark callouts?

### ISSUE THREAD

**Issue by carlorosati** [ridiculousfish/HexFiend#81]
any interest in this?

**Comment by carlorosati** [comment]
or maybe a pop out tray for numbered notes?

something like

---------
|abcdef|
|abcdef|

**Comment by carlorosati** [comment]
or maybe a pop out tray for numbered notes?

something like
```
HexFiend File Edit...
----------------_________
|123(1)abc|./?f|(1)      |
|1234^6abc|./?f|notes    |
|123456abc|./?f|(2)      |
|123456abc|./?f|different|
|123456abc|./?f|note     |
|123456abc|./?f|         |
|123456abc|./?f|         |
|123456abc|./?f|_________|
----------------
```

**Comment by carlorosati** [comment]
the numbers in the tray could be clickable

**Comment by kainjow** [comment]
I've never used bookmarks, so personally I wouldn't use this, but I can see the usefulness. Then again, TextEdit could work just as well ;)

**Comment by kainjow** [comment]
I have no plans to add this feature as there seems to be little interest. If anyone's interested feel free to comment here and/or work on it and create a pull request.
