### ISSUE TITLE
Line number format reverts to decimal

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#82]
Keeps reverting for some reason?

using Version 2.6 (170319)

edit: ah, could it be me clicking in the line number margin? will keep an eye on it

**Comment by kainjow** [comment]
You're right, looks like clicking the actual column doesn't affect the global setting.

**Comment by kainjow** [comment]
I've uploaded a beta [here](https://github.com/ridiculousfish/HexFiend/releases/tag/v2.7.0b1) if you'd like to try it.

**Comment by gingerbeardman** [comment]
@kainjow this beta crashes when searching for values in this file

https://cloud.githubusercontent.com/assets/49612/24750165/d13e737a-1abd-11e7-8ff2-bd942a06b5e3.gif

**Comment by kainjow** [comment]
Looks like it broke in db8ca34bd747ca68efa8bda59cc3023714326977. I'll take a look soon.

**Comment by kainjow** [comment]
Should be fixed as of 5858f53f9dae620f025d0bf5edfcb1f95d41c253.

**Comment by kainjow** [comment]
Beta 2 has been [posted](https://github.com/ridiculousfish/HexFiend/releases/tag/v2.7.0b2) if anyone would like to test.

**Comment by gingerbeardman** [comment]
Limited quick testing - it works well for me.
