### ISSUE TITLE
2.7b1: crash opening a JFIF and searching for FF

### ISSUE THREAD

**Issue by jasonbrackman** [ridiculousfish/HexFiend#83]
Image is 2700x2700 JFIF file (not sure if the size matters).  The previous non-beta version did not crash when doing this search.

**Comment by jspiro** [comment]
I found that given e.g. DF DF DF DF DF, if you search for DF, and hit cmd-g to find the next result, it crashes every time.

**Comment by kainjow** [comment]
There are some issues with the memory management changes done recently. I'll try to fix, if not back them all out. Unfortunately it'll be over a week until I can get to them. The v2.6 version should be stable though.

**Comment by kainjow** [comment]
Should be fixed as of 5858f53f9dae620f025d0bf5edfcb1f95d41c253.

**Comment by kainjow** [comment]
Beta 2 has been [posted](https://github.com/ridiculousfish/HexFiend/releases/tag/v2.7.0b2) if anyone would like to test.
