### ISSUE TITLE
Hex Fiend crashing

### ISSUE THREAD

**Issue by larsenv** [ridiculousfish/HexFiend#88]
I love Hex Fiend, but with the latest version sometimes when I try to find hex characters the application crashes.

How can I fix it? I know I'm being kind of vague but I would be happy to give some debug info if possible.

Thanks.

**Comment by kainjow** [comment]
What version are you using?

**Comment by larsenv** [comment]
I'm using version 2.6.

**Comment by kainjow** [comment]
See if you have any Hex Fiend crash report files at /Users/you/Library/Logs/DiagnosticReports/ and if so please attach them here.

**Comment by larsenv** [comment]
https://puu.sh/vJMlp/3c96f22b38.zip

Here they are.

**Comment by kainjow** [comment]
Can you try out the latest [beta](https://github.com/ridiculousfish/HexFiend/releases/tag/v2.70b3) and see if continues to crash?

**Comment by larsenv** [comment]
After spending a few days trying, I haven't had any crashes yet, but I'll let you know when I do.
