### ISSUE TITLE
Add preference to specify the default mode when opening files of a give type

### ISSUE THREAD

**Issue by splicer** [ridiculousfish/HexFiend#90]
1) "Hex Fiend" menu should have a "Preferences…" item, with the standard ⌘, keyboard shortcut.

2) In preferences, allow the user to specify the default mode (read-only, overwrite, or insert) when opening a file of a specific type, as well as the mode when open any other kind of file.

**Comment by kainjow** [comment]
For a while I've thought the current mode behavior is odd, and agree on having a preference to control it (default to Insert). However, what is the use case for a setting per file type? Can you give an example?
