### ISSUE TITLE
Allow administrator login to install command line tool

### ISSUE THREAD

**Issue by sprague252** [ridiculousfish/HexFiend#92]
When I try to install the command line tool, I get a dialog asking me to change permissions of the bin directory (actually /usr/local/bin). This is the incorrect behavior. There should be an administrator authentication dialog that allows me to install into this directory.

**Comment by kainjow** [comment]
I'm of the opinion that `/usr/local` should not be a root-owned folder, because it's not part of macOS. It's an optional folder. Homebrew uses this and doesn't require root. How are you managing these folders? Manually? Third-party software? Maybe you can chown the admin group?

I'd rather not have HF prompting for root permissions. If there is no clear solution, maybe HF can detect permission issues and suggest manual install.

**Comment by sprague252** [comment]
Thanks for your E-mail.  In every Unix/Linux system I have used /usr/local and its subdirectories are owned by root.  You install items from the command line using sudo and from the GUI by using an administrator authentication dialog.  Other GUI applications that install command line tools on the Mac do this (BBEdit is one example).  Users can create their own executable (bin) directories within their home directory structure and add them to their path.  I use ~/Library/bin for my user account to keep everything organized within the “Mac” layout, but you could use any structure you like.

The Homebrew recommendation to change ownership of /usr/local is a bit controversial among Unix/Linux folks.  That is certainly not the traditional way to do things.  See a discussion of this and some of the alternatives at the following URL.

https://apple.stackexchange.com/questions/1393/are-my-permissions-for-usr-local-correct <https://apple.stackexchange.com/questions/1393/are-my-permissions-for-usr-local-correct>

I do not use Homebrew myself, but I do use Anaconda for Python and R.  Anaconda installs into a directory in a user account on a Mac and expects the usr t be the owner, which can cause issues on a multiuser machine.  I have found a way to install into a directory within /opt.  That is really not the main point of the discussion, butI can give details if you would like.

Your application Hex Fiend is really useful.  Thank you for making it available.

-Mark

PS. I have an additional feature suggestion for Hex Fiend. It should have a read only mode to protect against unwittingly changing the file.  I usually use the app to inspect files that I so not want to change.  I realize I can just not save inadvertent changes, but an additional safeguard against changing the file would be nice.

**Comment by kainjow** [comment]
I think the safest solution for now would be to detect permission errors (the error text you see is what Cocoa returns), and suggest the user manually install and give a command that they can use to install (symlink from the current path).

> Your application Hex Fiend is really useful.  Thank you for making it available.

Not mine, I just help maintain it :)

**Comment by sprague252** [comment]
I do a lot of programming on the command line but not a lot of GUI app development.  There is an administrator authentication interface you can access when installing the command line tool (similar to sudo on the command line).  Many applications and installers use it.  I would suggest using that if there is a permission exception when installing the command line tool.  I am pretty sure that this requires Authorization Services, but I have never used it myself.  There is an explanation of Authentication Services with an example at the following URL.

https://developer.apple.com/library/content/documentation/Security/Conceptual/authorization_concepts/03authtasks/authtasks.html

-Mark

**Comment by kainjow** [comment]
Those docs suggest using AuthorizationExecuteWithPrivileges which has been deprecated for years. Unfortunately there is no direct replacement, and the modern alternative is not trivial.

**Comment by sprague252** [comment]
I think the replacement for AuthorizationExecuteWithPrivileges is to use the ServiceManagement.framework.  There is an example here.

https://developer.apple.com/library/content/samplecode/SMJobBless/Introduction/Intro.html#//apple_ref/doc/uid/DTS40010071-Intro-DontLinkElementID_2 <https://developer.apple.com/library/content/samplecode/SMJobBless/Introduction/Intro.html#//apple_ref/doc/uid/DTS40010071-Intro-DontLinkElementID_2>

-Mark

**Comment by kainjow** [comment]
I implemented this in a hacky with via AppleScript.

**Comment by sprague252** [comment]
Thanks. I will check it out.

-Mark
