### ISSUE TITLE
Copy to clipboard not working as expected?

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#94]
I seem to have been able to copy some text from Hex Fiend into my clipboard judging by the output of my clipboard manager (Alfred 3) but I cannot copy my selection on demand.

Any ideas?

**Comment by gingerbeardman** [comment]
My fault

**Comment by gingerbeardman** [comment]
So this is indeed problematic: https://transfer.sh/Vwj60/clipboard.mov (available for 14 days)

Not sure what is stopping it?

successful copy:
```
default	16:02:41.680844 +0100	pboard	Installing local data provider: (uuid:3B73F473-6898-4A8E-9371-A88FE0344664 gen: 149 item: 789514 flavor: 'dyn.ah62d4rv4gu8yuvwusmy1q2pyqzbhw7dfkf3he2p3nbvg82pwqvnhw6df') for gen: 149 index: 0 item: 789514
default	16:02:41.681299 +0100	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 149, <private>
default	16:02:41.681544 +0100	pboard	Installing local data provider: (uuid:85AB9F07-B8B7-4137-B16C-65E620362AFF gen: 149 item: 789514 flavor: 'public.utf8-plain-text') for gen: 149 index: 0 item: 789514
default	16:02:41.732213 +0100	pboard	Sending pasteboard update to server: <private>
default	16:02:41.732280 +0100	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	16:02:41.732669 +0100	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 149, <private>
```

unsuccessful copy:
```
default	16:02:49.256795 +0100	pboard	Installing local data provider: (uuid:ECADC411-C2B1-4805-97DF-4EF0AB2FEAC3 gen: 150 item: 789514 flavor: 'dyn.ah62d4rv4gu8yuvwusmy1q2pyqzbhw7dfkf3he2p3nbvg82pwqvnhw6df') for gen: 150 index: 0 item: 789514
default	16:02:49.257227 +0100	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 150, <private>
default	16:02:49.257456 +0100	pboard	Installing local data provider: (uuid:C6359E3A-E30C-4B09-8617-0E2C48A66D5C gen: 150 item: 789514 flavor: 'public.utf8-plain-text') for gen: 150 index: 0 item: 789514
default	16:02:49.308314 +0100	pboard	Sending pasteboard update to server: <private>
default	16:02:49.308419 +0100	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	16:02:49.308835 +0100	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 150, <private>
```

**Comment by kainjow** [comment]
I'm not so sure it's not working. What is this program you're using? What encoding are you using in Hex Fiend? You can test by copying into another Hex Fiend window and see if the exact same bytes show up. It could be that this program you're using is interpreting the text as UTF8 and these bytes aren't all UTF8.

**Comment by gingerbeardman** [comment]
I check my clipboard history with Alfred. I have also tried pasting into Atom and TextMate, no joy.
Encoding is Shift_JIS but I don't see any differences with other encoding.

You're right that I can copy the text into another Hex Fiend window.

So I guess the question is, at this point, how can I copy data from Hex Fiend into a text editor?

**Comment by kainjow** [comment]
What happens if you change the encoding to ASCII? Will it then copy all the bytes, even if it's junk?

**Comment by gingerbeardman** [comment]
Yes, ASCII copies all bytes. I'll use that in future for copy/paste.

Any idea what the other Hex editors are doing differently?

**Comment by kainjow** [comment]
I suppose copying plain text could have different interpretations. For example:

- Copy as text interpreting consecutive characters based on the current encoding. This is what it's currently doing.
- Copy as text using the displayed characters from the current encoding. So a displayed dot for non-printable character would be copied as the dot, not the raw character.
- Copy raw bytes as full ASCII.

Maybe there could be a preference to control what it does.

**Comment by gingerbeardman** [comment]
Works for me.

The other editors seem to be doing the first and last of those scenarios based on what the selected bytes, rather than a user preference.

**Comment by kainjow** [comment]
I implemented Edit > Copy as ASCII menu which activates when the Plain Text view is active.
