### ISSUE TITLE
Custom character encoding?

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#95]
Perhaps a _niche_ request, but it would be great to be able to specify a custom character encoding.

The vintage game data that I'm currently looking at uses a custom character set of 96 characters to allow display of Japanese text: some hiragana 0xB1-0xDF ([half-width kana](https://en.wikipedia.org/wiki/Half-width_kana) should go here, which is what Hex Fiend shows) and some katakana 0xE0-0xFF, with other supporting characters in 0xA0-0xB0. 

Remapping the characters could be as simple as an offset to the ASCII set, say 0x80 or -0x10, but in this case it would require a custom mapping:
```
...
B7=き
...
DD=ん
DE=゛
DF=゜
E0=ア
...
F0=フ
...
```
etc.

The English text in the game thankfully uses ASCII.

### Example of this feature in the wild (though it won't work for this specific case)
XVI32: Character conversion is performed using self-defined character tables
http://www.chmaas.handshake.de/delphi/freeware/xvi32/xviconv.htm

**Comment by kainjow** [comment]
Seems very niche. Personally I don't think I'll work on this feature. It probably wouldn't be that much work though, if you wanted to take a look (not sure what your Cocoa knowledge is). At a cursory glance it appears `copy1CharStringForByteValue()` is doing the work of converting bytes with the specific encoding. One potential design idea is to use an HFStringEncoding object everywhere and have subclasses for the built-in NSStringEncoding and a custom file mapping. But would take a fair amount of work to replace all the instances and update the code, and add UI support.

I will keep this issue open though to see if there's any other interest.

**Comment by gingerbeardman** [comment]
Thanks for your honest feedback. I'll try to take a look at this myself when and if I can.

**Comment by gingerbeardman** [comment]
Probably not what you want to hear but I wrote a quick Atom package in JavaScript to convert the text encoding for my current project.

**Comment by hansottowirtz** [comment]
I think this is called a `.tbl` file, https://www.reddit.com/r/mac/comments/1c4zav/mac_hex_editor_help/

**Comment by gingerbeardman** [comment]
also just found out about .cnv files that are produced from .ucm files according to the ICU spec

http://userguide.icu-project.org/conversion/data

**Comment by kainjow** [comment]
Seems like there's some more interest in this feature, so I created an experimental build:

https://github.com/ridiculousfish/HexFiend/releases/tag/v2.10b1

It works by loading JSON files at:

`~/Library/Application Support/com.ridiculousfish.HexFiend/Encodings`

Example:

```
{
  "name": "My Encoding",
  "map": {
    "01": "ü",
    "02": "d",
    "03": "f",
    "FF": "!"
  }
}
```

Currently only supports 1 byte encodings.

Files are loaded at launch and show up by "name" in the menu bar. Selection is saved to prefs as you'd expect.

Try it out and let me know what you think.

**Comment by gingerbeardman** [comment]
Good news. Where is the extra interest from? 

I need to use this with Japanese, so I'm happy to get involved with double byte support if you think I can be of help in any way?

**Comment by gingerbeardman** [comment]
I think an always 2-byte encoding would be useful to have.

My use can seems _mostly_ solved now that you have added this.

> Just a quick note that in this build `Other...` from the `Text Encoding` menu does nothing for me.

Here's the JSON I'd like to use (I use this for _Atom_ and _Synalize It! Pro_): https://pastebin.com/raw/2TxGKR2p

Here's what I got to work: https://pastebin.com/raw/Eg3RmAd7
- removed multi-byte mappings (I could split these for this build, urgh)
  - eg. `"0A0B0C": "KICK"`
- removed mappings to emoji
  - eg. `"0E0F": "🦇"`
- removed combinations of those two
  - eg. `"0809": "👦🤜"`

This is a mapping of a small amount of characters, so I guess it is activated over another standard base encoding? Which encoding would that be? None of the six in the Text Encoding menu from what I could see?

Anyway, I get what I want in the Plain Text View... which is good news!

![screen shot 2018-06-18 at 15 10 11](https://user-images.githubusercontent.com/49612/41541188-c70f0b80-7309-11e8-9420-02e2e7bec91f.png)

But there is currently no way for me to copy that Japanese text from either the Plain Text View or the Binary Templates View. I need to translate it or otherwise manipulate it.

So my requests:
- ability to copy from Plain Text and/or Binary Template Views
- ability to specify base encoding
- support for the multi-byte/emoji stuff I had to take out of my JSON

Nice work! Thanks

**Comment by kainjow** [comment]
I fixed the "Other" menu in 572e0dd.

For the "Plain Text" view, it is not using another encoding. For the binary templates view since you're using `ascii` then that's what it's translating as. So you're looking for a way to use the selected encoding instead of "ascii" for your binary template? Maybe we could have the encoding register itself with an identifier, and then the binary template can pick that up. Possibly a new `string` command that takes an encoding argument, with number of bytes.

Copying from the "Plain Text" view with a custom encoding should work as of eae7e50. As of 773dfc0 I added a "Copy Value" menu when you right-click on a template item.

**Comment by gingerbeardman** [comment]
Thanks very much! 

I'll try these out.

**Comment by gingerbeardman** [comment]
Did you have any further thoughts on the above: encoding identifier for use in binary templates?

**Comment by kainjow** [comment]
Closing in favor of #173 for the template integration discussion.
