### ISSUE TITLE
Can't update, read-only volume

### ISSUE THREAD

**Issue by Screenfeed** [ridiculousfish/HexFiend#99]
Hello.

It's something I see for a long time now, I'm still unable to update HexFiend via the "Check For Update..." menu. HexFiend keeps displaying a "Update Error":
>Hex Fiend can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move Hex Fiend to your Applications folder, relaunch it from there, and try again.

The thing is, it's not a read-only folder, it is in my Applications folder (the main one, not the user one), like all other applications.

Thanks.

PS: macOS Sierra 10.12.6.

**Comment by kainjow** [comment]
What do you mean you "see for a long time now"? Version 2.8 is the first version that has turned on auto-updates. Previous versions you had to manually install.

What version are you on currently that is failing to update?

**Comment by kainjow** [comment]
Are you using Path Finder by any chance?

**Comment by Screenfeed** [comment]
Hi.
I don't mean auto-updates, but clicking the "Check For Update..." menu item.
And by "see for a long time now", I mean I see this message since 2.5 at least, and probably before that.
As for Path Finder: yes, I use it.

**Comment by kainjow** [comment]
Looks like a [bug](https://github.com/sparkle-project/Sparkle/issues/936) related to Path Finder and Sparkle, the update framework Hex Fiend (and a lot of other apps) use.

**Comment by Screenfeed** [comment]
OK, thank you for your help.
